<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $title ?? 'GIATEP' }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-slate-50 text-slate-900 antialiased">
@php
$groups = [
 'Trabajo operativo'=>[['Inicio','dashboard.view','dashboard'],['Inicio administrativo','admin.dashboard','dashboard'],['Casos','cases.read','modules.cases.index'],['Investigaciones','investigations.read','modules.investigations.index'],['Revisiones y validaciones','reviews.read','modules.reviews.index'],['Observaciones','observations.read','modules.observations.index'],['Medidas y planes de acción','measures.read','modules.measures.index']],
 'Análisis'=>[['Dashboards y estadísticas','statistics.read','modules.statistics.index'],['Reportes','reports.export','modules.reports.index']],
 'Administración'=>[['Solicitudes de registro','registration-requests.review','admin.registration-requests.index'],['Usuarios','users.manage','admin.users.index'],['Roles y permisos','roles.manage','admin.roles.index'],['Establecimientos','establishments.manage','admin.establishments.index'],['Parámetros institucionales','settings.manage','admin.settings.index']],
 'Cuenta'=>[['Mi perfil','profile.read','modules.profile.index']],
];
@endphp
<div class="min-h-screen lg:grid lg:grid-cols-[18rem_1fr]">
<aside class="fixed inset-y-0 left-0 z-30 hidden w-72 flex-col bg-blue-950 text-white lg:static lg:flex lg:w-auto" data-sidebar><div class="border-b border-white/10 px-6 py-5"><div class="flex items-center justify-between"><a href="{{ route('dashboard') }}" class="text-2xl font-black tracking-tight">GIATEP</a><button type="button" class="text-2xl lg:hidden" data-menu-close aria-label="Cerrar menú">×</button></div><p class="mt-1 text-[10px] font-bold uppercase tracking-wider text-sky-200">Prototipo visual · Datos de demostración</p></div>
<nav class="flex-1 overflow-y-auto p-4" aria-label="Navegación principal">@foreach($groups as $group=>$items)@php $visible=collect($items)->filter(fn($item)=>auth()->user()->hasPermission($item[1])); @endphp @if($visible->isNotEmpty())<section class="mb-5"><p class="mb-2 px-3 text-[10px] font-black uppercase tracking-[.18em] text-sky-300">{{ $group }}</p><ul class="grid gap-1">@foreach($visible as [$label,$permission,$routeName])<li><a href="{{ route($routeName) }}" class="nav-link {{ request()->routeIs($routeName) ? 'nav-link-active' : '' }}">{{ $label }}</a></li>@endforeach</ul></section>@endif @endforeach</nav>
<div class="border-t border-white/10 p-4"><p class="px-3 text-xs font-bold uppercase tracking-wider text-sky-200">Establecimientos autorizados</p><p class="mt-2 px-3 text-sm text-white/80">{{ auth()->user()->establishments->map(fn($item)=>$item->type.' '.$item->name)->join(' · ') ?: 'Sin establecimiento asignado' }}</p><form method="POST" action="{{ route('logout') }}" class="mt-4">@csrf<button class="w-full rounded-lg border border-white/20 px-4 py-2 text-left font-bold hover:bg-white/10">Cerrar sesión</button></form></div></aside>
<div class="min-w-0"><header class="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur lg:px-8"><button type="button" class="btn-secondary lg:hidden" data-menu-toggle aria-expanded="false">Menú</button><div class="ml-auto text-right"><p class="font-bold">{{ auth()->user()->name }}</p><p class="text-xs text-slate-500">{{ auth()->user()->roles->pluck('name')->join(' · ') }}</p></div></header><main class="p-4 sm:p-6 lg:p-8">{{ $slot }}</main></div></div>
</body></html>
