<x-layouts.guest title='Solicitar acceso · GIATEP'>
<div class='mb-6'><a href='{{ route('login') }}' class='text-sm font-bold text-blue-800 hover:underline'>← Volver al inicio de sesión</a></div>
<div class='card p-6 sm:p-10'><p class='eyebrow'>Registro público</p><h2 class='mt-2 text-3xl font-bold'>Solicitar acceso a GIATEP</h2><p class='mt-2 text-slate-600'>Exclusivo para Delegados de Seguridad e integrantes del Comité Paritario. Tu cuenta quedará pendiente de revisión.</p>
<form method='POST' action='{{ route('register.store') }}' class='mt-8 grid gap-5 sm:grid-cols-2' data-submit-form>@csrf
    <div><label for='rut' class='label'>RUT</label><input id='rut' name='rut' value='{{ old('rut') }}' class='input' placeholder='12.345.678-5' required>@error('rut')<p class='error'>{{ $message }}</p>@enderror</div>
    <div><label for='name' class='label'>Nombre completo</label><input id='name' name='name' value='{{ old('name') }}' autocomplete='name' class='input' required>@error('name')<p class='error'>{{ $message }}</p>@enderror</div>
    <div><label for='job_title' class='label'>Cargo laboral</label><input id='job_title' name='job_title' value='{{ old('job_title') }}' class='input' required><p class='hint'>Tu función laboral, distinta del rol de acceso.</p>@error('job_title')<p class='error'>{{ $message }}</p>@enderror</div>
    <div><label for='establishment_id' class='label'>Establecimiento de trabajo</label><select id='establishment_id' name='establishment_id' class='input' required><option value=''>Selecciona una opción</option>@foreach($establishments as $establishment)<option value='{{ $establishment->id }}' @selected(old('establishment_id') == $establishment->id)>{{ $establishment->type }} · {{ $establishment->name }}</option>@endforeach</select>@error('establishment_id')<p class='error'>{{ $message }}</p>@enderror</div>
    <div class='sm:col-span-2'><label for='requested_role' class='label'>Rol solicitado</label><select id='requested_role' name='requested_role' class='input' required><option value=''>Selecciona una opción</option><option value='delegado' @selected(old('requested_role') === 'delegado')>Delegado de Seguridad</option><option value='cphs' @selected(old('requested_role') === 'cphs')>Integrante del Comité Paritario</option></select>@error('requested_role')<p class='error'>{{ $message }}</p>@enderror</div>
    <div><label for='email' class='label'>Correo electrónico</label><input id='email' name='email' type='email' value='{{ old('email') }}' autocomplete='email' class='input' required>@error('email')<p class='error'>{{ $message }}</p>@enderror</div>
    <div><label for='phone' class='label'>Teléfono de contacto</label><input id='phone' name='phone' value='{{ old('phone') }}' autocomplete='tel' class='input' required>@error('phone')<p class='error'>{{ $message }}</p>@enderror</div>
    <div><label for='password' class='label'>Contraseña</label><div class='relative'><input id='password' name='password' type='password' autocomplete='new-password' class='input pr-24' required><button type='button' class='password-toggle' data-password-toggle='password'>Mostrar</button></div>@error('password')<p class='error'>{{ $message }}</p>@enderror</div>
    <div><label for='password_confirmation' class='label'>Confirmar contraseña</label><input id='password_confirmation' name='password_confirmation' type='password' autocomplete='new-password' class='input' required></div>
    <div class='sm:col-span-2'><button type='submit' class='btn-primary w-full' data-submit-button>Enviar solicitud</button></div>
</form></div>
</x-layouts.guest>
