@php
$titles = [
    'cases' => ['Casos', 'Registro y seguimiento de accidentes del trabajo y enfermedades profesionales.'],
    'investigations' => ['Investigaciones', 'Expedientes, entrevistas, evidencias, hechos y análisis causal.'],
    'reviews' => ['Revisiones y validaciones', 'Bandeja técnica, observaciones e historial de decisiones.'],
    'observations' => ['Observaciones', 'Correcciones y respuestas vinculadas a los expedientes.'],
    'measures' => ['Medidas y planes de acción', 'Seguimiento de controles, responsables y vencimientos.'],
    'statistics' => ['Dashboards y estadísticas', 'Indicadores descriptivos construidos con datos de demostración.'],
    'reports' => ['Reportes', 'Catálogo, filtros y vista previa de informes.'],
    'profile' => ['Mi perfil', 'Datos personales, alcance y preferencias de esta demostración.'],
    'users' => ['Usuarios', 'Boceto de administración de cuentas sin modificar usuarios reales.'],
    'roles' => ['Roles y permisos', 'Matriz visual y configuración simulada.'],
    'establishments' => ['Establecimientos', 'Catálogo ficticio de centros de trabajo.'],
    'settings' => ['Parámetros institucionales', 'Catálogos y clasificaciones utilizados por el prototipo.'],
];
[$pageTitle, $pageDescription] = $titles[$module];
$changes = session(\App\Support\DemoWorkspace::SESSION_KEY, []);
$statusClass = fn ($status) => match ($status) { 'Vencida', 'Con observaciones' => 'status-rejected', 'Implementada', 'Concluida', 'Cerrado', 'Resuelta' => 'status-approved', default => 'status-pending' };
@endphp
<x-layouts.app :title="$pageTitle.' · GIATEP'">
<div class="mx-auto max-w-[1500px] space-y-6" data-demo-workspace data-demo-module="{{ $module }}">
    <nav class="text-sm text-slate-500" aria-label="Migas de pan"><a href="{{ route('dashboard') }}" class="hover:text-blue-800">Inicio</a><span class="mx-2">/</span><span class="font-semibold text-slate-800">{{ $pageTitle }}</span></nav>
    @if(session('demo_status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('demo_status') }}</div>@endif
    <section class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><p class="eyebrow">Prototipo visual · Datos de demostración</p><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{{ $pageTitle }}</h1><p class="mt-2 max-w-3xl text-slate-600">{{ $pageDescription }}</p></div>
        <div class="flex flex-wrap gap-2">
            @if(in_array($module, ['cases','users','establishments']))<a class="btn-primary inline-flex" href="{{ route('demo.show', ['module' => $module, 'mode' => 'create']) }}">+ Crear {{ $module === 'cases' ? 'caso' : ($module === 'users' ? 'usuario' : 'establecimiento') }}</a>@endif
            <form method="POST" action="{{ route('demo.reset') }}" data-confirm="¿Restablecer todos los cambios temporales de la demostración?">@csrf<button class="btn-secondary" type="submit">Restablecer demostración</button></form>
        </div>
    </section>

    @if($changes)<details class="card p-5"><summary class="cursor-pointer font-bold">Actividad temporal de esta sesión ({{ count($changes) }})</summary><ol class="mt-4 space-y-2 text-sm">@foreach(array_reverse($changes) as $change)<li><strong>{{ $change['at'] }}</strong> · {{ $change['action'] }} <span class="text-slate-500">por {{ $change['user'] }}</span></li>@endforeach</ol></details>@endif

    @if($module === 'cases')
        @if($mode === 'create' || $mode === 'edit')
            <form class="card overflow-hidden" method="POST" action="{{ route('demo.action', 'cases') }}" data-demo-form data-unsaved-form>@csrf<input type="hidden" name="action" value="{{ $mode === 'edit' ? 'Caso editado' : 'Caso registrado' }}"><input type="hidden" name="return_to" value="{{ route('modules.cases.index') }}">
                <div class="border-b border-slate-200 bg-slate-50 p-5"><div class="flex flex-wrap gap-2" data-step-nav>@foreach(['Trabajador','Establecimiento','Evento','Relato','Antecedentes','Resumen'] as $index => $step)<button type="button" class="step-pill {{ $index === 0 ? 'step-pill-active' : '' }}" data-step-target="{{ $index }}"><span>{{ $index + 1 }}</span>{{ $step }}</button>@endforeach</div></div>
                <div class="p-6 sm:p-8">
                    <section data-step="0" class="grid gap-5 md:grid-cols-2"><div><label class="label">RUT del trabajador</label><input class="input" value="{{ $selected['rut'] ?? '11.111.111-1' }}" required></div><div><label class="label">Nombre completo</label><input class="input" value="{{ $selected['worker'] ?? 'Camila Soto Rojas' }}" required></div><div><label class="label">Cargo</label><input class="input" value="Técnico en enfermería"></div><div><label class="label">Unidad</label><input class="input" value="Bodega clínica"></div></section>
                    <section data-step="1" class="hidden grid gap-5 md:grid-cols-2"><div><label class="label">Establecimiento</label><select class="input">@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select></div><div><label class="label">Tipo de vínculo</label><select class="input"><option>Funcionario/a</option><option>Honorarios</option><option>Empresa externa</option></select></div><div class="md:col-span-2"><label class="label">Lugar o dependencia</label><input class="input" value="Pasillo de acceso a bodega"></div></section>
                    <section data-step="2" class="hidden grid gap-5 md:grid-cols-2"><div><label class="label">Tipo de caso</label><select class="input" data-case-type><option>Accidente del trabajo</option><option>Enfermedad profesional</option></select></div><div><label class="label">Fecha del evento o diagnóstico</label><input type="date" class="input" value="2026-09-28"></div><div data-accident-field><label class="label">Hora</label><input type="time" class="input" value="10:35"></div><div data-accident-field><label class="label">Actividad realizada</label><input class="input" value="Traslado de insumos"></div><div data-disease-field class="hidden"><label class="label">Agente o factor de riesgo</label><input class="input" value="Agente químico irritante"></div><div data-disease-field class="hidden"><label class="label">Organismo calificador</label><input class="input" value="Organismo administrador"></div></section>
                    <section data-step="3" class="hidden"><label class="label">Relato inicial</label><textarea class="input" rows="8">{{ $selected['story'] ?? 'Durante el traslado de insumos, la trabajadora perdió estabilidad en una superficie húmeda.' }}</textarea><p class="hint">Registra hechos conocidos, sin conclusiones anticipadas.</p></section>
                    <section data-step="4" class="hidden grid gap-5 md:grid-cols-2"><div><label class="label">Lesión o diagnóstico</label><input class="input" value="{{ $selected['injury'] ?? 'Esguince de tobillo' }}"></div><div><label class="label">Parte del cuerpo</label><input class="input" value="{{ $selected['body_part'] ?? 'Tobillo derecho' }}"></div><div><label class="label">Calificación</label><select class="input"><option>Pendiente</option><option>Laboral</option><option>No laboral</option></select></div><div><label class="label">Documento de referencia</label><input type="file" class="input" data-local-file><p class="hint">Vista previa local; el archivo no se envía ni almacena.</p></div></section>
                    <section data-step="5" class="hidden space-y-5"><div class="rounded-xl bg-sky-50 p-5"><h3 class="font-bold text-sky-950">Resumen antes de registrar</h3><p class="mt-2 text-sm text-sky-900">Accidente del trabajo · Camila Soto Rojas · CESFAM Los Aromos · Calificación pendiente.</p></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Regla de demostración:</strong> un caso puede iniciar investigación cuando tiene antecedentes mínimos y el perfil posee permiso. Este criterio debe validarse antes de integración real.</div></section>
                </div>
                <div class="flex flex-wrap justify-between gap-3 border-t border-slate-200 bg-slate-50 p-5"><button type="button" class="btn-secondary" data-step-prev>Anterior</button><div class="flex gap-2"><button class="btn-secondary" name="action" value="Borrador de caso guardado">Guardar borrador</button><button type="button" class="btn-primary" data-step-next>Siguiente</button><button class="btn-primary hidden" data-step-submit>Registrar caso</button></div></div>
            </form>
        @elseif($selected)
            @php $relatedInvestigation = $selected['investigation_id'] ? $demo['investigations']->firstWhere('id', $selected['investigation_id']) : null; @endphp
            <div class="grid gap-6 xl:grid-cols-[1fr_22rem]"><section class="space-y-6"><div class="card p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="eyebrow">{{ $selected['id'] }}</p><h2 class="mt-1 text-2xl font-black">{{ $selected['worker'] }}</h2></div><span class="status {{ $statusClass($selected['status']) }}">{{ $selected['status'] }}</span></div><dl class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt>Tipo</dt><dd>{{ $selected['type'] }}</dd></div><div><dt>Fecha</dt><dd>{{ $selected['date'] }}</dd></div><div><dt>Establecimiento</dt><dd>{{ $selected['establishment'] }}</dd></div><div><dt>Calificación</dt><dd>{{ $selected['qualification'] }}</dd></div></dl></div>
                <div class="card p-6"><div class="tab-list" data-tabs>@foreach(['Resumen','Historial','Documentos','Investigación','Medidas'] as $i => $tab)<button class="tab-button {{ $i===0?'tab-button-active':'' }}" data-tab-target="case-{{ $i }}">{{ $tab }}</button>@endforeach</div><div class="mt-6" data-tab-panel="case-0"><h3 class="font-bold">Relato inicial</h3><p class="mt-2 text-slate-600">{{ $selected['story'] }}</p><dl class="mt-5 grid gap-4 sm:grid-cols-2"><div><dt>Lesión</dt><dd>{{ $selected['injury'] }}</dd></div><div><dt>Parte afectada</dt><dd>{{ $selected['body_part'] }}</dd></div></dl></div><div class="mt-6 hidden" data-tab-panel="case-1"><ul class="timeline"><li><strong>Caso registrado</strong><span>28/09/2026 · Usuario de demostración</span></li><li><strong>Antecedentes revisados</strong><span>29/09/2026 · Prevención de riesgos</span></li></ul></div><div class="mt-6 hidden" data-tab-panel="case-2"><div class="empty-state">No hay documentos almacenados. En el prototipo solo se previsualizan archivos locales.</div></div><div class="mt-6 hidden" data-tab-panel="case-3">@if($relatedInvestigation)<a class="text-link" href="{{ route('demo.show', ['module'=>'investigations','id'=>$relatedInvestigation['id']]) }}">Abrir {{ $relatedInvestigation['id'] }} · {{ $relatedInvestigation['status'] }}</a>@else<div class="empty-state">Aún no existe investigación asociada.</div>@endif</div><div class="mt-6 hidden" data-tab-panel="case-4"><ul class="space-y-3">@forelse($demo['measures']->where('case_id',$selected['id']) as $measure)<li class="rounded-xl border p-4"><strong>{{ $measure['description'] }}</strong><span class="status {{ $statusClass($measure['status']) }} ml-2">{{ $measure['status'] }}</span></li>@empty<li class="empty-state">Sin medidas asociadas.</li>@endforelse</ul></div></div></section>
                <aside class="space-y-3"><a class="btn-primary flex" href="{{ route('demo.show', ['module'=>'cases','id'=>$selected['id'],'mode'=>'edit']) }}">Editar caso</a><a class="btn-secondary flex" href="{{ route('demo.show', ['module'=>'investigations','id'=>$selected['investigation_id'] ?: 'INV-2026-011','mode'=>'edit']) }}">{{ $relatedInvestigation ? 'Continuar investigación' : 'Iniciar investigación' }}</a><div class="card p-5 text-sm"><strong>Separación de estados</strong><p class="mt-2 text-slate-600">La investigación puede concluir mientras las medidas y el caso continúan en seguimiento.</p></div></aside></div>
        @else
            <div class="filter-bar" data-filter-scope><input class="input" placeholder="Buscar trabajador o folio" data-table-search><select class="input" data-table-filter="type"><option value="">Todos los tipos</option><option>Accidente del trabajo</option><option>Enfermedad profesional</option></select><select class="input" data-table-filter="status"><option value="">Todos los estados</option>@foreach($demo['cases']->pluck('status')->unique() as $state)<option>{{ $state }}</option>@endforeach</select><select class="input"><option>Todos los establecimientos</option>@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select><input type="date" class="input"></div>
            <div class="card table-card"><table class="data-table"><thead><tr><th>Folio</th><th>Trabajador</th><th>Tipo</th><th>Establecimiento</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['cases'] as $case)<tr data-table-row data-type="{{ $case['type'] }}" data-status="{{ $case['status'] }}"><td class="font-bold">{{ $case['id'] }}</td><td>{{ $case['worker'] }}<small>{{ $case['rut'] }}</small></td><td>{{ $case['type'] }}</td><td>{{ $case['establishment'] }}</td><td>{{ $case['date'] }}</td><td><span class="status {{ $statusClass($case['status']) }}">{{ $case['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'cases','id'=>$case['id']]) }}">Ver detalle</a></td></tr>@endforeach</tbody></table><div class="empty-state m-5 hidden" data-filter-empty>No hay casos para los filtros seleccionados.</div></div>
        @endif
    @elseif($module === 'investigations')
        @if($selected)
            @php $case = $demo['cases']->firstWhere('id',$selected['case_id']); @endphp
            <div class="grid gap-6 xl:grid-cols-[15rem_1fr]"><aside class="card h-fit p-3"><p class="px-3 py-2 text-xs font-bold uppercase text-slate-500">Expediente {{ $selected['id'] }}</p>@foreach(['Antecedentes','Entrevistas','Evidencias','Relato final','Hechos','Árbol de causas','Matriz y medidas','Participantes','Propuesta IA','Resumen'] as $i=>$section)<button class="section-link {{ $i===0?'section-link-active':'' }}" data-section-target="inv-{{ $i }}">{{ $i+1 }}. {{ $section }}</button>@endforeach</aside>
            <form method="POST" action="{{ route('demo.action','investigations') }}" class="card min-w-0" data-unsaved-form>@csrf<input type="hidden" name="action" value="Borrador de investigación guardado"><input type="hidden" name="return_to" value="{{ url()->current() }}"><header class="border-b p-6"><div class="flex flex-wrap justify-between gap-4"><div><p class="eyebrow">{{ $selected['kind'] }} · {{ $case['id'] }}</p><h2 class="mt-1 text-2xl font-black">{{ $selected['id'] }}</h2></div><span class="status {{ $statusClass($selected['status']) }}">{{ $selected['status'] }}</span></div><div class="mt-4 h-2 rounded bg-slate-100"><div class="h-2 rounded bg-sky-600" style="width:{{ $selected['progress'] }}%"></div></div></header><div class="p-6 sm:p-8">
            <section data-section="inv-0"><h3 class="section-title">Antecedentes recuperados del caso</h3><div class="source-banner">Origen: {{ $case['id'] }} · Estos datos se muestran como referencia y no se editan aquí.</div><dl class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><div><dt>Trabajador</dt><dd>{{ $case['worker'] }}</dd></div><div><dt>Establecimiento</dt><dd>{{ $case['establishment'] }}</dd></div><div><dt>Evento</dt><dd>{{ $case['date'] }}</dd></div><div class="sm:col-span-2 lg:col-span-3"><dt>Relato inicial</dt><dd>{{ $case['story'] }}</dd></div></dl></section>
            <section data-section="inv-1" class="hidden"><h3 class="section-title">Entrevistas</h3><div class="grid gap-4 md:grid-cols-2"><input class="input" placeholder="Nombre del entrevistado" value="Daniela Araya"><select class="input"><option>Testigo presencial</option><option>Jefatura</option><option>Trabajador/a afectado/a</option></select><input class="input" placeholder="Cargo" value="Auxiliar de servicio"><input type="date" class="input" value="2026-09-24"><textarea class="input md:col-span-2" rows="5" placeholder="Declaración">Observé que el acceso se cerró mientras se trasladaba el carro.</textarea></div></section>
            <section data-section="inv-2" class="hidden"><h3 class="section-title">Evidencias</h3><label class="upload-zone"><input type="file" multiple data-local-file class="sr-only"><strong>Seleccionar archivos para vista previa local</strong><span>Los archivos no se almacenan ni se envían a un servidor.</span></label><ul class="mt-4 space-y-2" data-file-list></ul></section>
            <section data-section="inv-3" class="hidden"><h3 class="section-title">Relato cronológico final</h3><div class="source-banner mb-4"><strong>Referencia inicial:</strong> {{ $case['story'] }}</div><textarea class="input" rows="10">A las 10:35 horas, durante el traslado planificado de insumos, se produjo el evento descrito. La condición del lugar fue verificada posteriormente por el equipo investigador.</textarea></section>
            <section data-section="inv-4" class="hidden"><h3 class="section-title">Hechos constatados</h3><div class="space-y-3" data-repeat-list>@foreach(['H-01 · Se trasladaban insumos hacia la bodega.','H-02 · El piso presentaba humedad visible.','H-03 · No existía señalización preventiva instalada.','H-04 · La trabajadora perdió estabilidad.'] as $fact)<div class="repeat-row"><span class="drag-handle">⋮⋮</span><input class="input" value="{{ $fact }}"><button type="button" class="btn-secondary" data-remove-row>Quitar</button></div>@endforeach</div><button type="button" class="btn-secondary mt-4" data-add-fact>+ Agregar hecho</button></section>
            <section data-section="inv-5" class="hidden"><h3 class="section-title">Árbol de causas</h3><p class="mb-5 text-sm text-slate-600">Representación simplificada. Las relaciones no permiten conectar un hecho consigo mismo.</p><div class="cause-tree"><div class="cause-node cause-final">H-04 · Pérdida de estabilidad</div><div class="cause-connector">↑ Y ↑</div><div class="grid gap-4 md:grid-cols-2"><div class="cause-node">H-02 · Piso húmedo</div><div class="cause-node">H-03 · Sin señalización</div></div><div class="cause-connector">↑</div><div class="cause-node mx-auto">H-01 · Traslado de insumos</div></div><div class="mt-6 grid gap-4 sm:grid-cols-3"><select class="input"><option>H-02</option><option>H-03</option></select><select class="input"><option>antecede a</option><option>conjunción con</option><option>alternativa de</option></select><select class="input"><option>H-04</option><option>H-03</option></select></div></section>
            <section data-section="inv-6" class="hidden"><h3 class="section-title">Matriz de causas y medidas</h3><div class="card table-card shadow-none"><table class="data-table"><thead><tr><th>Hechos</th><th>Causa / código</th><th>Medida</th><th>Categoría</th><th>Responsable / plazo</th></tr></thead><tbody><tr><td>H-02 + H-03</td><td>Condición locativa · CL-04</td><td>Instalar señalización y definir inspección</td><td>Administrativa</td><td>Mantención · 07/10/2026</td></tr><tr><td>H-01</td><td>Traslado manual · TM-02</td><td>Revisar ruta de traslado</td><td>Ingeniería</td><td>Jefatura · 15/10/2026</td></tr></tbody></table></div></section>
            <section data-section="inv-7" class="hidden"><h3 class="section-title">Participantes</h3><div class="card table-card shadow-none"><table class="data-table"><thead><tr><th>Nombre</th><th>Cargo</th><th>Establecimiento</th><th>Función</th><th>Firma</th></tr></thead><tbody><tr><td>Paula Contreras</td><td>Prevencionista</td><td>Dirección Comunal</td><td>Coordinación</td><td><span class="status status-pending">Pendiente</span></td></tr><tr><td>Daniela Araya</td><td>Auxiliar de servicio</td><td>{{ $case['establishment'] }}</td><td>Testigo</td><td><span class="status status-pending">Pendiente</span></td></tr></tbody></table></div></section>
            <section data-section="inv-8" class="hidden"><h3 class="section-title">Ejemplo de propuesta IA</h3><div class="rounded-xl border border-violet-200 bg-violet-50 p-5"><p class="font-bold text-violet-950">Información que utilizaría este ejemplo</p><p class="mt-2 text-sm text-violet-900">Relato inicial, dos entrevistas, cuatro hechos y referencias visuales de evidencia. No se realiza análisis real ni se conecta un servicio externo.</p></div><button type="button" class="btn-primary mt-5" data-ai-example>Mostrar propuesta de ejemplo</button><div class="mt-5 hidden space-y-4" data-ai-result><div class="rounded-xl border p-5"><strong>Propuesta ficticia</strong><p class="mt-2 text-sm">Incorporar H-05: “La ruta habitual de traslado no estaba delimitada”. Relacionarlo como antecedente de H-01 y considerar una medida de ingeniería.</p></div><button type="button" class="btn-secondary" data-confirm-ai>Revisar e incorporar</button></div></section>
            <section data-section="inv-9" class="hidden"><h3 class="section-title">Resumen del expediente</h3><div class="grid gap-4 sm:grid-cols-3"><div class="metric"><span>Progreso</span><strong>{{ $selected['progress'] }}%</strong></div><div class="metric"><span>Estado</span><strong class="text-lg">{{ $selected['status'] }}</strong></div><div class="metric"><span>Pendiente</span><strong class="text-base">{{ $selected['pending'] }}</strong></div></div></section>
            </div><footer class="flex flex-wrap justify-between gap-3 border-t bg-slate-50 p-5"><button class="btn-secondary">Guardar borrador</button><div class="flex gap-2"><button name="action" value="Correcciones guardadas" class="btn-secondary">Corregir</button><button name="action" value="Investigación enviada a revisión" class="btn-primary">Enviar a revisión</button></div></footer></form></div>
        @else
            <div class="filter-bar"><input class="input" placeholder="Buscar folio o caso" data-table-search><select class="input" data-table-filter="status"><option value="">Todos los estados</option>@foreach($demo['investigations']->pluck('status')->unique() as $state)<option>{{ $state }}</option>@endforeach</select><select class="input"><option>Todos los responsables</option><option>Paula Contreras</option><option>Andrés Muñoz</option></select></div><div class="card table-card"><table class="data-table"><thead><tr><th>Investigación</th><th>Caso</th><th>Tipo</th><th>Responsable</th><th>Avance</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['investigations'] as $item)<tr data-table-row data-status="{{ $item['status'] }}"><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}</td><td>{{ $item['kind'] }}</td><td>{{ $item['owner'] }}</td><td><div class="progress"><span style="width:{{ $item['progress'] }}%"></span></div><small>{{ $item['progress'] }}%</small></td><td><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'investigations','id'=>$item['id']]) }}">Abrir</a></td></tr>@endforeach</tbody></table></div>
        @endif
    @elseif($module === 'reviews')
        @php $review = $selected ?: $demo['investigations']->whereIn('status',['Borrador','Con observaciones'])->first(); @endphp
        <div class="grid gap-6 xl:grid-cols-[1fr_25rem]"><section class="card table-card"><div class="border-b p-5"><h2 class="font-black">Bandeja de pendientes</h2></div><table class="data-table"><thead><tr><th>Expediente</th><th>Caso</th><th>Responsable</th><th>Pendiente</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['investigations']->whereIn('status',['Borrador','Con observaciones']) as $item)<tr><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}</td><td>{{ $item['owner'] }}</td><td>{{ $item['pending'] }}</td><td><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'reviews','id'=>$item['id']]) }}">Revisar</a></td></tr>@endforeach</tbody></table></section><aside class="card p-6"><p class="eyebrow">Expediente seleccionado</p><h2 class="mt-2 text-2xl font-black">{{ $review['id'] }}</h2><p class="mt-2 text-sm text-slate-600">{{ $review['pending'] }}</p><form class="mt-6 space-y-4" method="POST" action="{{ route('demo.action','reviews') }}">@csrf<input type="hidden" name="return_to" value="{{ url()->current() }}"><label class="label">Resultado</label><select class="input" name="action"><option>Correcciones solicitadas</option><option>Resultado de revisión registrado</option><option>Validación técnica registrada</option><option>Toma de conocimiento registrada</option></select><label class="label">Motivo u observación</label><textarea class="input" name="note" rows="5" required></textarea><button class="btn-primary w-full">Registrar decisión</button></form><div class="mt-6 border-t pt-5"><h3 class="font-bold">Historial</h3><ul class="timeline mt-3"><li><strong>Enviado a revisión</strong><span>Paula Contreras · Prevencionista · 01/10/2026</span></li><li><strong>Revisión asignada</strong><span>María José Fuentes · Prevencionista · 02/10/2026</span></li></ul></div><p class="mt-5 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">La validación técnica depende del permiso del rol; no se concede automáticamente al administrador.</p></aside></div>
    @elseif($module === 'observations')
        @php $observation = $selected ?: $demo['observations']->first(); @endphp
        <div class="filter-bar"><input class="input" placeholder="Caso o investigación" data-table-search><select class="input"><option>Todos los estados</option><option>Pendiente</option><option>Respondida</option><option>Resuelta</option></select><input type="date" class="input"></div><div class="grid gap-6 xl:grid-cols-[1fr_24rem]"><div class="card table-card"><table class="data-table"><thead><tr><th>Folio</th><th>Caso / investigación</th><th>Sección</th><th>Autor</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['observations'] as $item)<tr><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}<small>{{ $item['investigation_id'] }}</small></td><td>{{ $item['section'] }}</td><td>{{ $item['author'] }}<small>{{ $item['role'] }}</small></td><td>{{ $item['date'] }}</td><td><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'observations','id'=>$item['id']]) }}">Ver</a></td></tr>@endforeach</tbody></table></div><aside class="card p-6"><p class="eyebrow">{{ $observation['id'] }}</p><h2 class="mt-2 text-xl font-black">{{ $observation['section'] }}</h2><p class="mt-4 text-slate-700">{{ $observation['description'] }}</p><p class="mt-3 text-xs text-slate-500">{{ $observation['author'] }} · {{ $observation['role'] }} · {{ $observation['date'] }}</p><form method="POST" action="{{ route('demo.action','observations') }}" class="mt-6">@csrf<input type="hidden" name="action" value="Respuesta a observación registrada"><input type="hidden" name="return_to" value="{{ url()->current() }}"><label class="label">Respuesta o corrección realizada</label><textarea class="input" name="note" rows="5" required></textarea><button class="btn-primary mt-3 w-full">Responder observación</button></form></aside></div>
    @elseif($module === 'measures')
        @php $measure = $selected ?: $demo['measures']->first(); @endphp
        <div class="grid gap-4 sm:grid-cols-3"><div class="metric"><span>Pendientes</span><strong>{{ $demo['measures']->where('status','Pendiente')->count() }}</strong></div><div class="metric"><span>En ejecución</span><strong>{{ $demo['measures']->where('status','En ejecución')->count() }}</strong></div><div class="metric metric-danger"><span>Vencidas</span><strong>{{ $demo['measures']->where('status','Vencida')->count() }}</strong></div></div><div class="filter-bar"><input class="input" placeholder="Buscar medida o caso" data-table-search><select class="input"><option>Todos los estados</option><option>Pendiente</option><option>En ejecución</option><option>Implementada</option><option>Vencida</option></select><select class="input"><option>Todas las categorías</option><option>Ingeniería</option><option>Sustitución</option><option>Administrativa</option></select></div><div class="grid gap-6 xl:grid-cols-[1fr_25rem]"><div class="card table-card"><table class="data-table"><thead><tr><th>Medida</th><th>Caso</th><th>Descripción</th><th>Responsable</th><th>Plazo</th><th>Avance</th><th></th></tr></thead><tbody>@foreach($demo['measures'] as $item)<tr><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}<small>{{ $item['investigation_id'] }}</small></td><td>{{ $item['description'] }}<small>{{ $item['category'] }}</small></td><td>{{ $item['owner'] }}</td><td>{{ $item['due'] }}<br><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td>{{ $item['progress'] }}%</td><td><a class="text-link" href="{{ route('demo.show',['module'=>'measures','id'=>$item['id']]) }}">Editar</a></td></tr>@endforeach</tbody></table></div><aside class="card p-6"><p class="eyebrow">{{ $measure['id'] }} · {{ $measure['case_id'] }}</p><h2 class="mt-2 text-xl font-black">{{ $measure['description'] }}</h2><form method="POST" action="{{ route('demo.action','measures') }}" class="mt-6 space-y-4">@csrf<input type="hidden" name="return_to" value="{{ url()->current() }}"><label class="label">Avance</label><input type="range" min="0" max="100" value="{{ $measure['progress'] }}" class="w-full"><label class="label">Estado</label><select class="input" name="action"><option>Avance de medida registrado</option><option>Implementación simulada</option><option>Observación de medida registrada</option></select><label class="label">Observación</label><textarea class="input" name="note" rows="4"></textarea><label class="label">Evidencia local</label><input type="file" class="input" data-local-file><p class="hint">Vista previa local; no se almacena.</p><button class="btn-primary w-full">Guardar cambios</button></form></aside></div>
    @elseif($module === 'statistics')
        <div class="filter-bar" data-stat-filters><select class="input"><option>Todos los establecimientos</option>@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select><select class="input"><option>Últimos 12 meses</option><option>2026</option><option>Últimos 90 días</option></select><select class="input"><option>Todos los tipos</option><option>Accidente del trabajo</option><option>Enfermedad profesional</option></select><button class="btn-primary" type="button" data-refresh-stats>Actualizar resultados</button></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="metric"><span>Casos del período</span><strong data-stat-number>6</strong></div><div class="metric"><span>Investigaciones activas</span><strong data-stat-number>3</strong></div><div class="metric"><span>Medidas implementadas</span><strong data-stat-number>2</strong></div><div class="metric metric-danger"><span>Medidas vencidas</span><strong>1</strong></div></div><div class="grid gap-6 lg:grid-cols-2"><div class="card p-6"><h2 class="font-black">Casos por establecimiento</h2><div class="bar-chart mt-6">@foreach(['CESFAM Los Aromos'=>2,'SAR Central'=>2,'CECOSF Norte'=>1,'Posta Rural El Molino'=>1] as $label=>$value)<div><span>{{ $label }}</span><div><i style="width:{{ $value*35 }}%"></i></div><strong>{{ $value }}</strong></div>@endforeach</div></div><div class="card p-6"><h2 class="font-black">Distribución por tipo</h2><div class="donut-wrap mt-6"><div class="donut"></div><ul><li><i class="bg-sky-700"></i>Accidentes <strong>5</strong></li><li><i class="bg-amber-500"></i>Enfermedades <strong>1</strong></li></ul></div></div><div class="card p-6"><h2 class="font-black">Investigaciones por estado</h2><div class="bar-chart mt-6">@foreach($demo['investigations']->groupBy('status') as $state=>$items)<div><span>{{ $state }}</span><div><i style="width:{{ $items->count()*35 }}%"></i></div><strong>{{ $items->count() }}</strong></div>@endforeach</div></div><div class="card p-6"><h2 class="font-black">Lesiones o partes más frecuentes</h2><ol class="mt-5 space-y-3">@foreach(['Manos y dedos','Extremidades inferiores','Zona lumbar','Piel'] as $i=>$label)<li class="flex items-center gap-3"><span class="rank">{{ $i+1 }}</span><span class="flex-1">{{ $label }}</span><strong>{{ max(1,3-$i) }}</strong></li>@endforeach</ol></div></div><div class="empty-state hidden" data-stats-empty>No existen datos para la combinación seleccionada.</div>
    @elseif($module === 'reports')
        @php $reports=['Resumen de casos'=>'Listado consolidado por estado, tipo y establecimiento.','Informe de investigación'=>'Expediente con antecedentes, hechos, análisis y participantes.','Seguimiento de medidas'=>'Avances, vencimientos y evidencias declaradas.','Resumen por establecimiento'=>'Vista ejecutiva del alcance seleccionado.']; @endphp
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">@foreach($reports as $name=>$detail)<button type="button" class="report-card {{ $loop->first?'report-card-active':'' }}" data-report-type="{{ $name }}"><span>Informe</span><strong>{{ $name }}</strong><small>{{ $detail }}</small></button>@endforeach</div><div class="grid gap-6 lg:grid-cols-[20rem_1fr]"><aside class="card p-5"><h2 class="font-black">Configurar reporte</h2><div class="mt-5 space-y-4"><label class="label">Establecimiento</label><select class="input"><option>Todos</option>@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select><label class="label">Desde</label><input type="date" class="input" value="2026-01-01"><label class="label">Hasta</label><input type="date" class="input" value="2026-10-03"><button class="btn-primary w-full" type="button" data-report-preview>Actualizar vista previa</button><button class="btn-secondary w-full" type="button" onclick="window.print()">Imprimir / guardar como PDF</button><button class="btn-secondary w-full" disabled title="Pendiente de integración real">Exportar Excel · Pendiente</button></div></aside><section class="card p-6 print-card" data-report-output><div class="border-b pb-5"><p class="eyebrow">Vista previa · Datos de demostración</p><h2 class="mt-2 text-2xl font-black" data-report-title>Resumen de casos</h2><p class="mt-1 text-sm text-slate-500">Período 01/01/2026 al 03/10/2026 · Todos los establecimientos</p></div><div class="mt-6 grid gap-4 sm:grid-cols-3"><div class="metric"><span>Total</span><strong>6</strong></div><div class="metric"><span>Activos</span><strong>5</strong></div><div class="metric"><span>Cerrados</span><strong>1</strong></div></div><table class="data-table mt-6"><thead><tr><th>Folio</th><th>Tipo</th><th>Establecimiento</th><th>Estado</th></tr></thead><tbody>@foreach($demo['cases']->take(4) as $case)<tr><td>{{ $case['id'] }}</td><td>{{ $case['type'] }}</td><td>{{ $case['establishment'] }}</td><td>{{ $case['status'] }}</td></tr>@endforeach</tbody></table></section></div>
    @elseif($module === 'profile')
        <div class="grid gap-6 lg:grid-cols-[1fr_22rem]"><section class="card p-6 sm:p-8"><h2 class="text-xl font-black">Datos personales</h2><dl class="mt-6 grid gap-6 sm:grid-cols-2"><div><dt>Nombre</dt><dd>{{ auth()->user()->name }}</dd></div><div><dt>RUT</dt><dd>{{ auth()->user()->rut }}</dd></div><div><dt>Correo</dt><dd>{{ auth()->user()->email }}</dd></div><div><dt>Cargo</dt><dd>{{ auth()->user()->job_title ?: 'Sin información' }}</dd></div><div><dt>Roles</dt><dd>{{ auth()->user()->roles->pluck('name')->join(' · ') }}</dd></div><div><dt>Establecimientos</dt><dd>{{ auth()->user()->establishments->pluck('name')->join(' · ') ?: 'Sin establecimiento asignado' }}</dd></div></dl><p class="mt-6 rounded-xl bg-sky-50 p-4 text-sm text-sky-900">Los datos de cuenta son solo de consulta en este prototipo.</p></section><aside class="card p-6"><h2 class="font-black">Preferencias visuales</h2><form class="mt-5 space-y-4" method="POST" action="{{ route('demo.action','profile') }}">@csrf<input type="hidden" name="action" value="Preferencias visuales guardadas"><label class="flex items-center justify-between gap-4">Vista compacta<input type="checkbox" class="h-5 w-5"></label><label class="flex items-center justify-between gap-4">Reducir animaciones<input type="checkbox" class="h-5 w-5"></label><label class="label">Densidad de tablas</label><select class="input"><option>Cómoda</option><option>Compacta</option></select><button class="btn-primary w-full">Guardar en demostración</button></form></aside></div>
    @elseif(in_array($module,['users','roles','establishments','settings']))
        @php
        $adminData = [
          'users'=>[['Carolina Medina','Prevencionista','CESFAM Los Aromos','Activo'],['Pedro Arancibia','Comité Paritario','SAR Central','Activo'],['Natalia Bustos','Jefatura Directa','CECOSF Norte','Suspendido']],
          'roles'=>[['Administrador','6 permisos','3 usuarios','Activo'],['Prevencionista','8 permisos','5 usuarios','Activo'],['Comité Paritario','6 permisos','12 usuarios','Activo']],
          'establishments'=>[['CESFAM Los Aromos','CESFAM','Av. Los Aromos 125','contacto@demo.test'],['SAR Central','SAR','Av. Central 980','sar@demo.test'],['CECOSF Norte','CECOSF','Pasaje Norte 44','norte@demo.test']],
          'settings'=>[['Tipos de caso','2 valores','Accidente · Enfermedad profesional','Activo'],['Categorías de control','5 valores','Eliminación · Sustitución · Ingeniería…','Activo'],['Estados de investigación','5 valores','Borrador · Revisión · Concluida…','Activo']],
        ][$module];
        @endphp
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Administración simulada:</strong> estas acciones no crean ni modifican usuarios, roles, establecimientos o parámetros reales.</div><div class="filter-bar"><input class="input" placeholder="Buscar" data-table-search><select class="input"><option>Todos los estados</option><option>Activo</option><option>Suspendido</option></select><button class="btn-primary" type="button" data-open-demo-modal>+ Nuevo registro</button></div><div class="card table-card"><table class="data-table"><thead><tr><th>Nombre</th><th>Tipo / rol</th><th>Alcance / detalle</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($adminData as $row)<tr data-table-row><td class="font-bold">{{ $row[0] }}</td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td><span class="status {{ $row[3]==='Activo'?'status-approved':'status-pending' }}">{{ $row[3] }}</span></td><td><button class="text-link" type="button" data-open-demo-modal data-record="{{ $row[0] }}">Ver / editar</button></td></tr>@endforeach</tbody></table></div>
        @if($module==='roles')<div class="card p-6"><h2 class="font-black">Matriz visual de permisos</h2><div class="table-card mt-5"><table class="data-table"><thead><tr><th>Permiso</th><th>Administrador</th><th>Prevencionista</th><th>Comité Paritario</th></tr></thead><tbody>@foreach(['Ver casos','Investigar','Revisar expedientes','Gestionar medidas','Ver estadísticas','Administrar usuarios'] as $i=>$permission)<tr><td>{{ $permission }}</td><td><input type="checkbox" @checked($i===5)></td><td><input type="checkbox" @checked($i<5)></td><td><input type="checkbox" @checked(in_array($i,[0,1,3]))></td></tr>@endforeach</tbody></table></div></div>@endif
        <dialog class="demo-dialog" data-demo-modal><form method="POST" action="{{ route('demo.action',$module) }}" class="card p-6">@csrf<input type="hidden" name="action" value="Registro administrativo simulado guardado"><div class="flex items-start justify-between"><div><p class="eyebrow">Datos ficticios</p><h2 class="mt-1 text-xl font-black" data-modal-title>Nuevo registro</h2></div><button type="button" class="btn-secondary" data-close-demo-modal>×</button></div><div class="mt-6 grid gap-4"><label class="label">Nombre</label><input class="input" required><label class="label">Tipo o rol</label><select class="input"><option>Activo</option><option>En revisión</option></select><label class="label">Detalle</label><textarea class="input" rows="4"></textarea></div><button class="btn-primary mt-6 w-full">Guardar en demostración</button></form></dialog>
    @endif
</div>
</x-layouts.app>
