@php
$titles = [
    'cases' => ['Casos', 'Registro y seguimiento de accidentes del trabajo y enfermedades profesionales.'],
    'investigations' => ['Investigaciones', 'Expedientes, entrevistas, evidencias, hechos y análisis causal.'],
    'reviews' => ['Revisiones y validaciones', 'Bandeja técnica, observaciones e historial de decisiones.'],
    'observations' => ['Observaciones', 'Correcciones y respuestas vinculadas a los expedientes.'],
    'measures' => ['Medidas y planes de acción', 'Seguimiento de controles, responsables y vencimientos.'],
    'statistics' => ['Dashboards y estadísticas', 'Indicadores descriptivos construidos con datos de demostración.'],
    'reports' => ['Reportes', 'Catálogo, filtros y vista previa de informes.'],
    'profile' => ['Mi perfil', 'Datos personales, alcance y preferencias de esta demostración.'],
    'users' => ['Usuarios', 'Boceto de administración de cuentas sin modificar usuarios reales.'],
    'roles' => ['Roles y permisos', 'Matriz visual y configuración simulada.'],
    'establishments' => ['Establecimientos', 'Catálogo ficticio de centros de trabajo.'],
    'settings' => ['Parámetros institucionales', 'Catálogos y clasificaciones utilizados por el prototipo.'],
];
[$pageTitle, $pageDescription] = $titles[$module];
$changes = session(\App\Support\DemoWorkspace::SESSION_KEY, []);
$statusClass = fn ($status) => match ($status) { 'Vencida', 'Con observaciones' => 'status-rejected', 'Implementada', 'Concluida', 'Cerrado', 'Resuelta' => 'status-approved', default => 'status-pending' };
@endphp
<x-layouts.app :title="$pageTitle.' · GIATEP'">
<div class="mx-auto max-w-[1500px] space-y-6" data-demo-workspace data-demo-module="{{ $module }}">
    <nav class="text-sm text-slate-500" aria-label="Migas de pan"><a href="{{ route('dashboard') }}" class="hover:text-blue-800">Inicio</a><span class="mx-2">/</span><span class="font-semibold text-slate-800">{{ $pageTitle }}</span></nav>
    @if(session('demo_status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('demo_status') }}</div>@endif
    <section class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><p class="eyebrow">Prototipo visual · Datos de demostración</p><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{{ $pageTitle }}</h1><p class="mt-2 max-w-3xl text-slate-600">{{ $pageDescription }}</p></div>
        <div class="flex flex-wrap gap-2">
            @if(in_array($module, ['cases','users','establishments']))<a class="btn-primary inline-flex" href="{{ route('demo.show', ['module' => $module, 'mode' => 'create']) }}">+ Crear {{ $module === 'cases' ? 'caso' : ($module === 'users' ? 'usuario' : 'establecimiento') }}</a>@endif
            <form method="POST" action="{{ route('demo.reset') }}" data-confirm="¿Restablecer todos los cambios temporales de la demostración?">@csrf<button class="btn-secondary" type="submit">Restablecer demostración</button></form>
        </div>
    </section>

    @if($changes)<details class="card p-5"><summary class="cursor-pointer font-bold">Actividad temporal de esta sesión ({{ count($changes) }})</summary><ol class="mt-4 space-y-2 text-sm">@foreach(array_reverse($changes) as $change)<li><strong>{{ $change['at'] }}</strong> · {{ $change['action'] }} <span class="text-slate-500">por {{ $change['user'] }}</span></li>@endforeach</ol></details>@endif

    @if($module === 'cases')
        @if($mode === 'create' || $mode === 'edit')
            <form class="card overflow-hidden" method="POST" action="{{ route('demo.action', 'cases') }}" data-demo-form data-unsaved-form>@csrf<input type="hidden" name="action" value="{{ $mode === 'edit' ? 'Caso editado' : 'Caso registrado' }}"><input type="hidden" name="return_to" value="{{ route('modules.cases.index') }}">
                <div class="border-b border-slate-200 bg-slate-50 p-5"><div class="flex flex-wrap gap-2" data-step-nav>@foreach(['Trabajador','Establecimiento','Evento','Relato','Antecedentes','Resumen'] as $index => $step)<button type="button" class="step-pill {{ $index === 0 ? 'step-pill-active' : '' }}" data-step-target="{{ $index }}"><span>{{ $index + 1 }}</span>{{ $step }}</button>@endforeach</div></div>
                <div class="p-6 sm:p-8">
                    <section data-step="0" class="grid gap-5 md:grid-cols-2"><div><label class="label">RUT del trabajador</label><input class="input" value="{{ $selected['rut'] ?? '11.111.111-1' }}" required></div><div><label class="label">Nombre completo</label><input class="input" value="{{ $selected['worker'] ?? 'Camila Soto Rojas' }}" required></div><div><label class="label">Cargo</label><input class="input" value="Técnico en enfermería"></div><div><label class="label">Unidad</label><input class="input" value="Bodega clínica"></div></section>
                    <section data-step="1" class="hidden grid gap-5 md:grid-cols-2"><div><label class="label">Establecimiento</label><select class="input">@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select></div><div><label class="label">Tipo de vínculo</label><select class="input"><option>Funcionario/a</option><option>Honorarios</option><option>Empresa externa</option></select></div><div class="md:col-span-2"><label class="label">Lugar o dependencia</label><input class="input" value="Pasillo de acceso a bodega"></div></section>
                    <section data-step="2" class="hidden grid gap-5 md:grid-cols-2"><div><label class="label">Tipo de caso</label><select class="input" data-case-type><option>Accidente del trabajo</option><option>Enfermedad profesional</option></select></div><div><label class="label">Fecha del evento o diagnóstico</label><input type="date" class="input" value="2026-09-28"></div><div data-accident-field><label class="label">Hora</label><input type="time" class="input" value="10:35"></div><div data-accident-field><label class="label">Actividad realizada</label><input class="input" value="Traslado de insumos"></div><div data-disease-field class="hidden"><label class="label">Agente o factor de riesgo</label><input class="input" value="Agente químico irritante"></div><div data-disease-field class="hidden"><label class="label">Organismo calificador</label><input class="input" value="Organismo administrador"></div></section>
                    <section data-step="3" class="hidden"><label class="label">Relato inicial</label><textarea class="input" rows="8">{{ $selected['story'] ?? 'Durante el traslado de insumos, la trabajadora perdió estabilidad en una superficie húmeda.' }}</textarea><p class="hint">Registra hechos conocidos, sin conclusiones anticipadas.</p></section>
                    <section data-step="4" class="hidden grid gap-5 md:grid-cols-2"><div><label class="label">Lesión o diagnóstico</label><input class="input" value="{{ $selected['injury'] ?? 'Esguince de tobillo' }}"></div><div><label class="label">Parte del cuerpo</label><input class="input" value="{{ $selected['body_part'] ?? 'Tobillo derecho' }}"></div><div><label class="label">Calificación</label><select class="input"><option>Pendiente</option><option>Laboral</option><option>No laboral</option></select></div><div><label class="label">Documento de referencia</label><input type="file" class="input" data-local-file><p class="hint">Vista previa local; el archivo no se envía ni almacena.</p></div></section>
                    <section data-step="5" class="hidden space-y-5"><div class="rounded-xl bg-sky-50 p-5"><h3 class="font-bold text-sky-950">Resumen antes de registrar</h3><p class="mt-2 text-sm text-sky-900">Accidente del trabajo · Camila Soto Rojas · CESFAM Los Aromos · Calificación pendiente.</p></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Regla de demostración:</strong> un caso puede iniciar investigación cuando tiene antecedentes mínimos y el perfil posee permiso. Este criterio debe validarse antes de integración real.</div></section>
                </div>
                <div class="flex flex-wrap justify-between gap-3 border-t border-slate-200 bg-slate-50 p-5"><button type="button" class="btn-secondary" data-step-prev>Anterior</button><div class="flex gap-2"><button class="btn-secondary" name="action" value="Borrador de caso guardado">Guardar borrador</button><button type="button" class="btn-primary" data-step-next>Siguiente</button><button class="btn-primary hidden" data-step-submit>Registrar caso</button></div></div>
            </form>
        @elseif($selected)
            @php $relatedInvestigation = $selected['investigation_id'] ? $demo['investigations']->firstWhere('id', $selected['investigation_id']) : null; @endphp
            <div class="grid gap-6 xl:grid-cols-[1fr_22rem]"><section class="space-y-6"><div class="card p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="eyebrow">{{ $selected['id'] }}</p><h2 class="mt-1 text-2xl font-black">{{ $selected['worker'] }}</h2></div><span class="status {{ $statusClass($selected['status']) }}">{{ $selected['status'] }}</span></div><dl class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt>Tipo</dt><dd>{{ $selected['type'] }}</dd></div><div><dt>Fecha</dt><dd>{{ $selected['date'] }}</dd></div><div><dt>Establecimiento</dt><dd>{{ $selected['establishment'] }}</dd></div><div><dt>Calificación</dt><dd>{{ $selected['qualification'] }}</dd></div></dl></div>
                <div class="card p-6"><div class="tab-list" data-tabs>@foreach(['Resumen','Historial','Documentos','Investigación','Medidas'] as $i => $tab)<button class="tab-button {{ $i===0?'tab-button-active':'' }}" data-tab-target="case-{{ $i }}">{{ $tab }}</button>@endforeach</div><div class="mt-6" data-tab-panel="case-0"><h3 class="font-bold">Relato inicial</h3><p class="mt-2 text-slate-600">{{ $selected['story'] }}</p><dl class="mt-5 grid gap-4 sm:grid-cols-2"><div><dt>Lesión</dt><dd>{{ $selected['injury'] }}</dd></div><div><dt>Parte afectada</dt><dd>{{ $selected['body_part'] }}</dd></div></dl></div><div class="mt-6 hidden" data-tab-panel="case-1"><ul class="timeline"><li><strong>Caso registrado</strong><span>28/09/2026 · Usuario de demostración</span></li><li><strong>Antecedentes revisados</strong><span>29/09/2026 · Prevención de riesgos</span></li></ul></div><div class="mt-6 hidden" data-tab-panel="case-2"><div class="empty-state">No hay documentos almacenados. En el prototipo solo se previsualizan archivos locales.</div></div><div class="mt-6 hidden" data-tab-panel="case-3">@if($relatedInvestigation)<a class="text-link" href="{{ route('demo.show', ['module'=>'investigations','id'=>$relatedInvestigation['id']]) }}">Abrir {{ $relatedInvestigation['id'] }} · {{ $relatedInvestigation['status'] }}</a>@else<div class="empty-state">Aún no existe investigación asociada.</div>@endif</div><div class="mt-6 hidden" data-tab-panel="case-4"><ul class="space-y-3">@forelse($demo['measures']->where('case_id',$selected['id']) as $measure)<li class="rounded-xl border p-4"><strong>{{ $measure['description'] }}</strong><span class="status {{ $statusClass($measure['status']) }} ml-2">{{ $measure['status'] }}</span></li>@empty<li class="empty-state">Sin medidas asociadas.</li>@endforelse</ul></div></div></section>
                <aside class="space-y-3"><a class="btn-primary flex" href="{{ route('demo.show', ['module'=>'cases','id'=>$selected['id'],'mode'=>'edit']) }}">Editar caso</a><a class="btn-secondary flex" href="{{ $relatedInvestigation ? route('demo.show', ['module'=>'investigations','id'=>$selected['investigation_id'],'mode'=>'edit']) : route('modules.investigations.index', ['case'=>$selected['id']]) }}">{{ $relatedInvestigation ? 'Continuar investigación' : 'Iniciar investigación' }}</a><div class="card p-5 text-sm"><strong>Separación de estados</strong><p class="mt-2 text-slate-600">La investigación puede concluir mientras las medidas y el caso continúan en seguimiento.</p></div></aside></div>
        @else
            <div class="filter-bar" data-filter-scope><input class="input" placeholder="Buscar trabajador o folio" data-table-search><select class="input" data-table-filter="type"><option value="">Todos los tipos</option><option>Accidente del trabajo</option><option>Enfermedad profesional</option></select><select class="input" data-table-filter="status"><option value="">Todos los estados</option>@foreach($demo['cases']->pluck('status')->unique() as $state)<option>{{ $state }}</option>@endforeach</select><select class="input"><option>Todos los establecimientos</option>@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select><input type="date" class="input"></div>
            <div class="card table-card"><table class="data-table"><thead><tr><th>Folio</th><th>Trabajador</th><th>Tipo</th><th>Establecimiento</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['cases'] as $case)<tr data-table-row data-type="{{ $case['type'] }}" data-status="{{ $case['status'] }}"><td class="font-bold">{{ $case['id'] }}</td><td>{{ $case['worker'] }}<small>{{ $case['rut'] }}</small></td><td>{{ $case['type'] }}</td><td>{{ $case['establishment'] }}</td><td>{{ $case['date'] }}</td><td><span class="status {{ $statusClass($case['status']) }}">{{ $case['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'cases','id'=>$case['id']]) }}">Ver detalle</a></td></tr>@endforeach</tbody></table><div class="empty-state m-5 hidden" data-filter-empty>No hay casos para los filtros seleccionados.</div></div>
        @endif
    @elseif($module === 'investigations')
        @if($selected)
            @php $case = $demo['cases']->firstWhere('id',$selected['case_id']); @endphp
            <div class="grid gap-6 xl:grid-cols-[15rem_1fr]"><aside class="card h-fit p-3"><p class="px-3 py-2 text-xs font-bold uppercase text-slate-500">Expediente {{ $selected['id'] }}</p>@foreach(['Antecedentes generales','Entrevistas','Evidencias','Relato final','Hechos','Árbol de causas','Matriz y medidas','Participantes','Resumen'] as $i=>$section)<button class="section-link {{ $i===0?'section-link-active':'' }} {{ in_array($i, [4,5,6]) ? 'hidden' : '' }}" data-section-target="inv-{{ $i }}" @if(in_array($i, [4,5,6])) data-ai-derived-nav @endif>{{ $i+1 }}. {{ $section }}</button>@endforeach</aside>
            <form method="POST" action="{{ route('demo.action','investigations') }}" class="card min-w-0" data-unsaved-form>@csrf<input type="hidden" name="action" value="Borrador de investigación guardado"><input type="hidden" name="return_to" value="{{ url()->current() }}"><header class="border-b p-6"><div class="flex flex-wrap justify-between gap-4"><div><p class="eyebrow">{{ $selected['kind'] }} · {{ $case['id'] }}</p><h2 class="mt-1 text-2xl font-black">{{ $selected['id'] }}</h2></div><span class="status {{ $statusClass($selected['status']) }}">{{ $selected['status'] }}</span></div><div class="mt-4 h-2 rounded bg-slate-100"><div class="h-2 rounded bg-sky-600" style="width:{{ $selected['progress'] }}%"></div></div></header><div class="p-6 sm:p-8">
            <section data-section="inv-0"><h3 class="section-title">Antecedentes generales</h3><div class="source-banner">Información recuperada del caso {{ $case['id'] }}. Puede corregirse o completarse para la investigación.</div>
                <div class="mt-6 space-y-6">
                    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">1.1 Datos del empleador</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label><span class="label">Nombre de la empresa</span><input class="input" name="employer_name" value="{{ $case['employer_name'] ?? 'Dirección Comunal de Salud' }}"></label><label><span class="label">RUT de la empresa</span><input class="input" name="employer_rut" value="{{ $case['employer_rut'] ?? '69.170.100-K' }}"></label><label><span class="label">Organismo administrador</span><input class="input" name="administrator" value="{{ $case['administrator'] ?? 'ACHS' }}"></label><label><span class="label">Actividad económica</span><input class="input" name="economic_activity" value="Salud municipal"></label><label class="md:col-span-2"><span class="label">Dirección</span><input class="input" name="employer_address" value="{{ $case['employer_address'] ?? $case['establishment'] }}"></label></div></fieldset>
                    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">1.2 Datos del trabajador o trabajadora</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label><span class="label">Nombre completo</span><input class="input" name="worker_name" value="{{ $case['worker'] }}"></label><label><span class="label">RUT</span><input class="input" name="worker_rut" value="{{ $case['rut'] }}"></label><label><span class="label">Profesión u oficio</span><input class="input" name="job_title" value="{{ $case['job_title'] ?? '' }}"></label><label><span class="label">Teléfono</span><input class="input" name="worker_phone" value="{{ $case['phone'] ?? '' }}"></label><label><span class="label">Fecha de ingreso</span><input type="date" class="input" name="hire_date"></label><label><span class="label">Antigüedad en el puesto</span><input class="input" name="job_tenure"></label></div></fieldset>
                    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">1.3 Datos del accidente o suceso</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label><span class="label">Fecha</span><input type="date" class="input" name="event_date" value="{{ $case['date'] }}"></label><label><span class="label">Hora</span><input type="time" class="input" name="event_time" value="{{ $case['time'] ?? '' }}"></label><label><span class="label">Lugar</span><input class="input" name="event_location" value="{{ $case['location'] ?? $case['establishment'] }}"></label><label><span class="label">Tipo de evento</span><input class="input" name="event_type" value="{{ $case['type'] }}"></label><label class="md:col-span-2"><span class="label">Relato inicial recuperado</span><textarea class="input" name="initial_story" rows="5">{{ $case['story'] }}</textarea></label></div></fieldset>
                </div>
            </section>
            <section data-section="inv-1" class="hidden" data-interviews-workspace>
                <div data-interview-list>
                    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="section-title mb-1">Entrevistas</h3><p class="text-sm text-slate-600">Personas entrevistadas durante la investigación.</p></div><div class="flex flex-wrap gap-2"><button type="button" class="btn-secondary" data-create-legacy-interview>+ Crear entrevista anterior</button><button type="button" class="btn-primary" data-create-interview>+ Crear entrevista</button></div></div>
                    <div class="card table-card mt-5 shadow-none"><table class="data-table"><thead><tr><th>Entrevistado</th><th>Tipo de testigo</th><th>Cargo</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody data-interview-rows><tr><td class="font-bold">Daniela Araya</td><td>Testigo presencial directo</td><td>Auxiliar de servicio</td><td>24/09/2026</td><td><span class="status status-approved">Completada</span></td><td><button type="button" class="text-link" data-create-interview>Ver / editar</button></td></tr></tbody></table></div>
                </div>
                <div class="hidden" data-interview-editor data-interview-form>
                <div class="mb-5 flex items-center justify-between gap-3"><div><p class="eyebrow">Nueva entrevista</p><h3 class="mt-1 text-xl font-black" data-interview-form-title>Formulario de entrevista</h3></div><button type="button" class="btn-secondary" data-cancel-interview>← Volver a la lista</button></div>
                <div class="mb-5 hidden rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800" data-interview-validation role="alert">Complete las preguntas obligatorias marcadas con * para guardar la entrevista.</div>
                <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                    <label><span class="label">Tipo de testigo</span><select class="input" name="witness_type" data-witness-type><option value="affected">Trabajador accidentado</option><option value="direct" selected>Testigo presencial directo</option><option value="indirect">Testigo presencial indirecto</option><option value="context">Testigo de contexto o circunstancial</option><option value="supervisor">Supervisor o jefatura</option><option value="technical">Testigo técnico o especialista</option><option value="institutional">Testigo institucional</option><option value="documentary">Testigo documental</option><option value="emergency">Testigo de respuesta a la emergencia</option></select></label>
                    <label><span class="label">Fecha de entrevista</span><input type="date" class="input" name="interview_date" value="2026-09-24"></label>
                    <label><span class="label">Nombre completo</span><input class="input" name="interviewee_name" value="Daniela Araya"></label>
                    <label><span class="label">RUT</span><input class="input" name="interviewee_rut" placeholder="12.345.678-9"></label>
                    <label><span class="label">Cargo</span><input class="input" name="interviewee_role" value="Auxiliar de servicio"></label>
                    <label><span class="label">Empresa</span><input class="input" name="interviewee_company" value="Dirección Comunal de Salud"></label>
                    <label><span class="label">Hora de inicio</span><input type="time" class="input" name="interview_start_time"></label>
                    <label><span class="label">Lugar de entrevista</span><input class="input" name="interview_location"></label>
                </div>
                <fieldset disabled class="mt-6 hidden space-y-5" aria-hidden="true" data-legacy-questionnaire>
                    <fieldset class="rounded-xl border border-slate-200 p-4 sm:p-5" data-question-group="chronology">
                        <legend class="px-2 font-black text-blue-950">4. Reconstrucción cronológica de los hechos</legend>
                        <div class="mt-3 grid gap-4">
                            @foreach(['¿Qué trabajo o actividad se estaba realizando?', '¿Cuál era el objetivo de la tarea?', '¿Quiénes participaban?', '¿Dónde se realizaba?', '¿Cuánto tiempo llevaba realizando esta actividad?', '¿Qué ocurrió exactamente?', '¿Qué estaba haciendo en ese momento?', '¿Qué hicieron las demás personas presentes?', '¿Hubo algún evento inesperado o anormal?', '¿Qué ocurrió inmediatamente después?', '¿Quién prestó ayuda?', '¿Se aplicó algún procedimiento de emergencia?'] as $question)
                                <div data-development-question>
                                    <div class="flex items-start justify-between gap-3"><label for="chronology-detail-{{ $loop->index }}" class="text-sm font-semibold text-slate-800">{{ $question }}</label><label class="flex shrink-0 cursor-pointer items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold"><input type="checkbox" name="chronology_not_applicable[]" value="{{ $loop->index }}" data-development-na>No aplica</label></div>
                                    <textarea id="chronology-detail-{{ $loop->index }}" class="input mt-2" rows="2" name="chronology_detail[]"></textarea>
                                </div>
                            @endforeach
                        </div>
                    </fieldset>

                    @php
                    $variationQuestions = [
                        ['¿La tarea era habitual?', 'yes', 'Describa cómo se realizaba habitualmente'],
                        ['¿Se estaba realizando de la misma forma que normalmente?', 'no', 'Explique qué era diferente'],
                        ['¿La actividad se realizó en el lugar habitual?', 'no', 'Indique qué diferencias existían respecto del lugar habitual'],
                        ['¿La tarea se realizó en el horario habitual?', 'no', 'Explique la diferencia de horario'],
                        ['¿Utilizaba el equipo habitual?', 'no', 'Indique qué equipo o herramienta era diferente'],
                        ['¿Se utilizaron materiales o productos habituales?', 'no', 'Indique cuáles eran diferentes'],
                    ];
                    @endphp
                    <fieldset class="rounded-xl border border-slate-200 p-4 sm:p-5" data-question-group="task">
                        <legend class="px-2 font-black text-blue-950">5. Análisis de variaciones</legend>
                        <div class="mt-2 divide-y divide-slate-100">
                            @foreach($variationQuestions as [$question, $detailWhen, $placeholder])
                                <div class="py-4" data-conditional-detail data-detail-when="{{ $detailWhen }}">
                                    <div class="grid gap-3 lg:grid-cols-[minmax(0,1fr)_18rem] lg:items-center"><p class="text-sm font-semibold text-slate-800">{{ $question }}</p><div class="grid grid-cols-3 gap-2">@foreach(['yes' => 'Sí', 'no' => 'No', 'na' => 'No aplica'] as $value => $answer)<label class="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-slate-300 px-2 py-3 text-xs font-bold"><input type="radio" name="variation_answer_{{ $loop->parent->index }}" value="{{ $value }}">{{ $answer }}</label>@endforeach</div></div>
                                    <label class="mt-3 hidden" data-conditional-input><span class="label">{{ $placeholder }}</span><textarea class="input" rows="2" name="variation_detail[]" disabled></textarea></label>
                                </div>
                            @endforeach
                        </div>
                    </fieldset>

                    <fieldset class="rounded-xl border border-slate-200 p-4 sm:p-5" data-question-group="environment">
                        <legend class="px-2 font-black text-blue-950">6. Condiciones del entorno</legend>
                        <div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach(['Piso resbaladizo','Desorden','Iluminación insuficiente','Espacio reducido','Obstáculos','Desniveles','Señalización insuficiente','Ruido elevado','Frío','Calor','Lluvia','Viento','Polvo','Sustancias químicas'] as $condition)<label class="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" name="environment_conditions[]" value="{{ $condition }}" class="size-4">{{ $condition }}</label>@endforeach<label class="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" name="environment_conditions[]" value="Otro" class="size-4" data-toggle-other="environment-other">Otro</label></div>
                        <label class="mt-4 hidden" data-other-field="environment-other"><span class="label">Especifique otra condición</span><input class="input" name="other_environment_condition" disabled></label>
                    </fieldset>

                    <fieldset class="rounded-xl border border-slate-200 p-4 sm:p-5" data-question-group="protection">
                        <legend class="px-2 font-black text-blue-950">7. Equipos de protección personal</legend>
                        <div data-yes-options><div class="grid gap-3 lg:grid-cols-[minmax(0,1fr)_18rem] lg:items-center"><p class="text-sm font-semibold text-slate-800">¿La tarea requería elementos de protección personal?</p><div class="grid grid-cols-3 gap-2">@foreach(['yes' => 'Sí', 'no' => 'No', 'na' => 'No aplica'] as $value => $answer)<label class="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-slate-300 px-2 py-3 text-xs font-bold"><input type="radio" name="ppe_required" value="{{ $value }}">{{ $answer }}</label>@endforeach</div></div>
                            <div class="mt-4 hidden" data-yes-options-panel><p class="label">EPP utilizados</p><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach(['Casco','Guantes','Lentes','Zapatos de seguridad','Arnés'] as $ppe)<label class="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" name="ppe_used[]" value="{{ $ppe }}" class="size-4">{{ $ppe }}</label>@endforeach<label class="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" name="ppe_used[]" value="Otro" class="size-4" data-toggle-other="ppe-other">Otro</label></div><label class="mt-4 hidden" data-other-field="ppe-other"><span class="label">Especifique otro EPP</span><input class="input" name="other_ppe" disabled></label></div>
                        </div>
                    </fieldset>

                    <fieldset class="rounded-xl border border-slate-200 p-4 sm:p-5" data-question-group="training">
                        <legend class="px-2 font-black text-blue-950">8. Información y capacitación</legend>
                        <div data-yes-options><div class="grid gap-3 lg:grid-cols-[minmax(0,1fr)_18rem] lg:items-center"><p class="text-sm font-semibold text-slate-800">¿Recibió instrucción para realizar esta tarea?</p><div class="grid grid-cols-3 gap-2">@foreach(['yes' => 'Sí', 'no' => 'No', 'na' => 'No aplica'] as $value => $answer)<label class="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-slate-300 px-2 py-3 text-xs font-bold"><input type="radio" name="instruction_received" value="{{ $value }}">{{ $answer }}</label>@endforeach</div></div>
                            <div class="mt-4 hidden" data-yes-options-panel><p class="label">Tipo de instrucción recibida</p><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach(['Verbal','Escrita','Capacitación formal','Procedimiento de Trabajo Seguro','AST'] as $instruction)<label class="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" name="instruction_types[]" value="{{ $instruction }}" class="size-4">{{ $instruction }}</label>@endforeach</div></div>
                        </div>
                    </fieldset>
                    <label class="block"><span class="label">Relato libre o información adicional</span><textarea class="input" name="statement" rows="7">Observé que el acceso se cerró mientras se trasladaba el carro.</textarea></label>
                </fieldset>
                @include('modules.investigations.partials.interview-questionnaire')
                <div class="mt-6 flex flex-col-reverse gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:justify-end"><button type="button" class="btn-secondary" data-cancel-interview>Cancelar</button><button type="button" class="btn-primary" data-save-interview>Guardar entrevista</button></div>
                </div>
            </section>
            <section data-section="inv-2" class="hidden"><h3 class="section-title">Evidencias</h3><div class="mb-5 grid gap-4 md:grid-cols-3"><label><span class="label">Tipo de evidencia</span><select class="input"><option>Fotografía</option><option>Video o grabación</option><option>Documento o registro</option><option>Procedimiento de trabajo</option><option>Registro de capacitación</option><option>Registro de mantención</option><option>Permiso de trabajo</option><option>Otro</option></select></label><label><span class="label">Origen</span><input class="input" placeholder="Persona, equipo o sistema"></label><label><span class="label">Fecha de obtención</span><input type="date" class="input"></label></div><label class="mb-5 block"><span class="label">Descripción y relación con los hechos</span><textarea class="input" rows="3"></textarea></label><label class="upload-zone"><input type="file" multiple data-local-file class="sr-only"><strong>Seleccionar archivos para vista previa local</strong><span>Los archivos no se almacenan ni se envían a un servidor.</span></label><ul class="mt-4 space-y-2" data-file-list></ul></section>
            <section data-section="inv-3" class="hidden" data-final-story-ai>
                <h3 class="section-title">Relato cronológico final</h3>
                <div class="source-banner"><strong>Información disponible:</strong> relato inicial, antecedentes editados, entrevistas y evidencias incorporadas a la investigación.</div>
                <label for="final-investigation-story" class="mt-5 block"><span class="label">Relato final de la investigación</span><textarea id="final-investigation-story" class="input" name="final_story" rows="10" placeholder="Redacte la secuencia final de los hechos a partir de los antecedentes verificados."></textarea><span class="hint">Debe ser redactado y revisado por el prevencionista, Comité Paritario o delegado responsable.</span></label>
                <div class="mt-5 rounded-xl border border-violet-200 bg-violet-50 p-5">
                    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold text-violet-950">Propuesta de análisis con IA</p><p class="mt-1 text-sm text-violet-900">Analiza el relato final para detectar hechos, proponer el árbol de causas y preparar medidas.</p></div><button type="button" class="btn-primary shrink-0" data-final-ai-generate>Analizar relato final</button></div>
                    <p class="mt-4 hidden text-sm font-semibold text-red-700" data-final-ai-error role="alert">Escriba el relato final antes de solicitar el análisis.</p>
                    <p class="mt-4 hidden text-sm font-semibold text-violet-900" data-final-ai-loading role="status">Preparando propuesta…</p>
                </div>
                <div class="mt-5 hidden space-y-6" data-final-ai-result>
                    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Hechos detectados</legend><div class="mt-3 space-y-3" data-ai-facts>@foreach(['H-01 · Se trasladaban insumos hacia la bodega.','H-02 · El piso presentaba humedad visible.','H-03 · No existía señalización preventiva instalada.','H-04 · La trabajadora perdió estabilidad.'] as $fact)<input class="input" name="ai_facts[]" value="{{ $fact }}" disabled>@endforeach</div></fieldset>
                    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Árbol de causas propuesto</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label><span class="label">Hecho final</span><input class="input" name="ai_tree_final" value="H-04 · Pérdida de estabilidad" disabled></label><label><span class="label">Antecedente principal</span><input class="input" name="ai_tree_origin" value="H-01 · Traslado de insumos" disabled></label><label><span class="label">Causa 1</span><input class="input" name="ai_tree_cause[]" value="H-02 · Piso húmedo" disabled></label><label><span class="label">Causa 2</span><input class="input" name="ai_tree_cause[]" value="H-03 · Sin señalización" disabled></label></div></fieldset>
                    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Medidas propuestas</legend><div class="mt-3 space-y-4" data-ai-measures>@foreach([['Instalar señalización y definir inspección','Administrativa','Mantención','2026-10-07'],['Revisar la ruta de traslado','Ingeniería','Jefatura','2026-10-15']] as [$measure,$category,$owner,$due])<div class="grid gap-3 rounded-xl bg-slate-50 p-4 lg:grid-cols-[1fr_11rem_12rem_11rem]" data-ai-measure><label><span class="label">Medida</span><textarea class="input" name="ai_measure_description[]" rows="2" disabled>{{ $measure }}</textarea></label><label><span class="label">Categoría</span><input class="input" name="ai_measure_category[]" value="{{ $category }}" disabled></label><label><span class="label">Responsable</span><input class="input" name="ai_measure_owner[]" value="{{ $owner }}" disabled></label><label><span class="label">Plazo</span><input type="date" class="input" name="ai_measure_due[]" value="{{ $due }}" disabled></label></div>@endforeach</div></fieldset>
                    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p class="hint">Revise y edite toda la propuesta antes de incorporarla a la investigación.</p><button type="button" class="btn-primary shrink-0" data-save-ai-proposal>Guardar propuesta</button></div>
                    <p class="hidden rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900" data-ai-saved-status role="status">Propuesta incorporada. Se habilitaron los apartados correspondientes.</p>
                </div>
            </section>
            <section data-section="inv-4" class="hidden"><h3 class="section-title">Hechos constatados</h3><div class="space-y-3" data-derived-facts></div><button type="button" class="btn-secondary mt-4" data-add-fact>+ Agregar hecho</button></section>
            <section data-section="inv-5" class="hidden"><h3 class="section-title">Árbol de causas</h3><p class="mb-5 text-sm text-slate-600">Resultado incorporado desde la propuesta revisada.</p><div class="cause-tree" data-derived-tree></div></section>
            <section data-section="inv-6" class="hidden"><h3 class="section-title">Matriz de causas y medidas</h3><div class="card table-card shadow-none"><table class="data-table"><thead><tr><th>Medida</th><th>Categoría</th><th>Responsable</th><th>Plazo</th></tr></thead><tbody data-derived-measures></tbody></table></div></section>
            <section data-section="inv-7" class="hidden"><h3 class="section-title">Participantes</h3><div class="card table-card shadow-none"><table class="data-table"><thead><tr><th>Nombre</th><th>Cargo</th><th>Establecimiento</th><th>Función</th><th>Firma</th></tr></thead><tbody><tr><td>Paula Contreras</td><td>Prevencionista</td><td>Dirección Comunal</td><td>Coordinación</td><td><span class="status status-pending">Pendiente</span></td></tr><tr><td>Daniela Araya</td><td>Auxiliar de servicio</td><td>{{ $case['establishment'] }}</td><td>Testigo</td><td><span class="status status-pending">Pendiente</span></td></tr></tbody></table></div></section>
            <section data-section="inv-8" class="hidden"><h3 class="section-title">Resumen del expediente</h3><div class="grid gap-4 sm:grid-cols-3"><div class="metric"><span>Progreso</span><strong>{{ $selected['progress'] }}%</strong></div><div class="metric"><span>Estado</span><strong class="text-lg">{{ $selected['status'] }}</strong></div><div class="metric"><span>Pendiente</span><strong class="text-base">{{ $selected['pending'] }}</strong></div></div></section>
            </div><footer class="flex flex-wrap justify-between gap-3 border-t bg-slate-50 p-5"><button class="btn-secondary">Guardar borrador</button><div class="flex gap-2"><button name="action" value="Correcciones guardadas" class="btn-secondary">Corregir</button><button name="action" value="Investigación enviada a revisión" class="btn-primary">Enviar a revisión</button></div></footer></form></div>
        @else
            <div class="filter-bar"><input class="input" placeholder="Buscar folio o caso" data-table-search><select class="input" data-table-filter="status"><option value="">Todos los estados</option>@foreach($demo['investigations']->pluck('status')->unique() as $state)<option>{{ $state }}</option>@endforeach</select><select class="input"><option>Todos los responsables</option><option>Paula Contreras</option><option>Andrés Muñoz</option></select></div><div class="card table-card"><table class="data-table"><thead><tr><th>Investigación</th><th>Caso</th><th>Tipo</th><th>Responsable</th><th>Avance</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['investigations'] as $item)<tr data-table-row data-status="{{ $item['status'] }}"><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}</td><td>{{ $item['kind'] }}</td><td>{{ $item['owner'] }}</td><td><div class="progress"><span style="width:{{ $item['progress'] }}%"></span></div><small>{{ $item['progress'] }}%</small></td><td><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'investigations','id'=>$item['id']]) }}">Abrir</a></td></tr>@endforeach</tbody></table></div>
        @endif
    @elseif($module === 'reviews')
        @php $review = $selected ?: $demo['investigations']->whereIn('status',['Borrador','Con observaciones'])->first(); @endphp
        <div class="grid gap-6 xl:grid-cols-[1fr_25rem]"><section class="card table-card"><div class="border-b p-5"><h2 class="font-black">Bandeja de pendientes</h2></div><table class="data-table"><thead><tr><th>Expediente</th><th>Caso</th><th>Responsable</th><th>Pendiente</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['investigations']->whereIn('status',['Borrador','Con observaciones']) as $item)<tr><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}</td><td>{{ $item['owner'] }}</td><td>{{ $item['pending'] }}</td><td><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'reviews','id'=>$item['id']]) }}">Revisar</a></td></tr>@endforeach</tbody></table></section><aside class="card p-6"><p class="eyebrow">Expediente seleccionado</p><h2 class="mt-2 text-2xl font-black">{{ $review['id'] }}</h2><p class="mt-2 text-sm text-slate-600">{{ $review['pending'] }}</p><form class="mt-6 space-y-4" method="POST" action="{{ route('demo.action','reviews') }}">@csrf<input type="hidden" name="return_to" value="{{ url()->current() }}"><label class="label">Resultado</label><select class="input" name="action"><option>Correcciones solicitadas</option><option>Resultado de revisión registrado</option><option>Validación técnica registrada</option><option>Toma de conocimiento registrada</option></select><label class="label">Motivo u observación</label><textarea class="input" name="note" rows="5" required></textarea><button class="btn-primary w-full">Registrar decisión</button></form><div class="mt-6 border-t pt-5"><h3 class="font-bold">Historial</h3><ul class="timeline mt-3"><li><strong>Enviado a revisión</strong><span>Paula Contreras · Prevencionista · 01/10/2026</span></li><li><strong>Revisión asignada</strong><span>María José Fuentes · Prevencionista · 02/10/2026</span></li></ul></div><p class="mt-5 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">La validación técnica depende del permiso del rol; no se concede automáticamente al administrador.</p></aside></div>
    @elseif($module === 'observations')
        @php $observation = $selected ?: $demo['observations']->first(); @endphp
        <div class="filter-bar"><input class="input" placeholder="Caso o investigación" data-table-search><select class="input"><option>Todos los estados</option><option>Pendiente</option><option>Respondida</option><option>Resuelta</option></select><input type="date" class="input"></div><div class="grid gap-6 xl:grid-cols-[1fr_24rem]"><div class="card table-card"><table class="data-table"><thead><tr><th>Folio</th><th>Caso / investigación</th><th>Sección</th><th>Autor</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($demo['observations'] as $item)<tr><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}<small>{{ $item['investigation_id'] }}</small></td><td>{{ $item['section'] }}</td><td>{{ $item['author'] }}<small>{{ $item['role'] }}</small></td><td>{{ $item['date'] }}</td><td><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td><a class="text-link" href="{{ route('demo.show',['module'=>'observations','id'=>$item['id']]) }}">Ver</a></td></tr>@endforeach</tbody></table></div><aside class="card p-6"><p class="eyebrow">{{ $observation['id'] }}</p><h2 class="mt-2 text-xl font-black">{{ $observation['section'] }}</h2><p class="mt-4 text-slate-700">{{ $observation['description'] }}</p><p class="mt-3 text-xs text-slate-500">{{ $observation['author'] }} · {{ $observation['role'] }} · {{ $observation['date'] }}</p><form method="POST" action="{{ route('demo.action','observations') }}" class="mt-6">@csrf<input type="hidden" name="action" value="Respuesta a observación registrada"><input type="hidden" name="return_to" value="{{ url()->current() }}"><label class="label">Respuesta o corrección realizada</label><textarea class="input" name="note" rows="5" required></textarea><button class="btn-primary mt-3 w-full">Responder observación</button></form></aside></div>
    @elseif($module === 'measures')
        @php $measure = $selected ?: $demo['measures']->first(); @endphp
        <div class="grid gap-4 sm:grid-cols-3"><div class="metric"><span>Pendientes</span><strong>{{ $demo['measures']->where('status','Pendiente')->count() }}</strong></div><div class="metric"><span>En ejecución</span><strong>{{ $demo['measures']->where('status','En ejecución')->count() }}</strong></div><div class="metric metric-danger"><span>Vencidas</span><strong>{{ $demo['measures']->where('status','Vencida')->count() }}</strong></div></div><div class="filter-bar"><input class="input" placeholder="Buscar medida o caso" data-table-search><select class="input"><option>Todos los estados</option><option>Pendiente</option><option>En ejecución</option><option>Implementada</option><option>Vencida</option></select><select class="input"><option>Todas las categorías</option><option>Ingeniería</option><option>Sustitución</option><option>Administrativa</option></select></div><div class="grid gap-6 xl:grid-cols-[1fr_25rem]"><div class="card table-card"><table class="data-table"><thead><tr><th>Medida</th><th>Caso</th><th>Descripción</th><th>Responsable</th><th>Plazo</th><th>Avance</th><th></th></tr></thead><tbody>@foreach($demo['measures'] as $item)<tr><td class="font-bold">{{ $item['id'] }}</td><td>{{ $item['case_id'] }}<small>{{ $item['investigation_id'] }}</small></td><td>{{ $item['description'] }}<small>{{ $item['category'] }}</small></td><td>{{ $item['owner'] }}</td><td>{{ $item['due'] }}<br><span class="status {{ $statusClass($item['status']) }}">{{ $item['status'] }}</span></td><td>{{ $item['progress'] }}%</td><td><a class="text-link" href="{{ route('demo.show',['module'=>'measures','id'=>$item['id']]) }}">Editar</a></td></tr>@endforeach</tbody></table></div><aside class="card p-6"><p class="eyebrow">{{ $measure['id'] }} · {{ $measure['case_id'] }}</p><h2 class="mt-2 text-xl font-black">{{ $measure['description'] }}</h2><form method="POST" action="{{ route('demo.action','measures') }}" class="mt-6 space-y-4">@csrf<input type="hidden" name="return_to" value="{{ url()->current() }}"><label class="label">Avance</label><input type="range" min="0" max="100" value="{{ $measure['progress'] }}" class="w-full"><label class="label">Estado</label><select class="input" name="action"><option>Avance de medida registrado</option><option>Implementación simulada</option><option>Observación de medida registrada</option></select><label class="label">Observación</label><textarea class="input" name="note" rows="4"></textarea><label class="label">Evidencia local</label><input type="file" class="input" data-local-file><p class="hint">Vista previa local; no se almacena.</p><button class="btn-primary w-full">Guardar cambios</button></form></aside></div>
    @elseif($module === 'statistics')
        <div class="filter-bar" data-stat-filters><select class="input"><option>Todos los establecimientos</option>@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select><select class="input"><option>Últimos 12 meses</option><option>2026</option><option>Últimos 90 días</option></select><select class="input"><option>Todos los tipos</option><option>Accidente del trabajo</option><option>Enfermedad profesional</option></select><button class="btn-primary" type="button" data-refresh-stats>Actualizar resultados</button></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="metric"><span>Casos del período</span><strong data-stat-number>6</strong></div><div class="metric"><span>Investigaciones activas</span><strong data-stat-number>3</strong></div><div class="metric"><span>Medidas implementadas</span><strong data-stat-number>2</strong></div><div class="metric metric-danger"><span>Medidas vencidas</span><strong>1</strong></div></div><div class="grid gap-6 lg:grid-cols-2"><div class="card p-6"><h2 class="font-black">Casos por establecimiento</h2><div class="bar-chart mt-6">@foreach(['CESFAM Los Aromos'=>2,'SAR Central'=>2,'CECOSF Norte'=>1,'Posta Rural El Molino'=>1] as $label=>$value)<div><span>{{ $label }}</span><div><i style="width:{{ $value*35 }}%"></i></div><strong>{{ $value }}</strong></div>@endforeach</div></div><div class="card p-6"><h2 class="font-black">Distribución por tipo</h2><div class="donut-wrap mt-6"><div class="donut"></div><ul><li><i class="bg-sky-700"></i>Accidentes <strong>5</strong></li><li><i class="bg-amber-500"></i>Enfermedades <strong>1</strong></li></ul></div></div><div class="card p-6"><h2 class="font-black">Investigaciones por estado</h2><div class="bar-chart mt-6">@foreach($demo['investigations']->groupBy('status') as $state=>$items)<div><span>{{ $state }}</span><div><i style="width:{{ $items->count()*35 }}%"></i></div><strong>{{ $items->count() }}</strong></div>@endforeach</div></div><div class="card p-6"><h2 class="font-black">Lesiones o partes más frecuentes</h2><ol class="mt-5 space-y-3">@foreach(['Manos y dedos','Extremidades inferiores','Zona lumbar','Piel'] as $i=>$label)<li class="flex items-center gap-3"><span class="rank">{{ $i+1 }}</span><span class="flex-1">{{ $label }}</span><strong>{{ max(1,3-$i) }}</strong></li>@endforeach</ol></div></div><div class="empty-state hidden" data-stats-empty>No existen datos para la combinación seleccionada.</div>
    @elseif($module === 'reports')
        @php $reports=['Resumen de casos'=>'Listado consolidado por estado, tipo y establecimiento.','Informe de investigación'=>'Expediente con antecedentes, hechos, análisis y participantes.','Seguimiento de medidas'=>'Avances, vencimientos y evidencias declaradas.','Resumen por establecimiento'=>'Vista ejecutiva del alcance seleccionado.']; @endphp
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">@foreach($reports as $name=>$detail)<button type="button" class="report-card {{ $loop->first?'report-card-active':'' }}" data-report-type="{{ $name }}"><span>Informe</span><strong>{{ $name }}</strong><small>{{ $detail }}</small></button>@endforeach</div><div class="grid gap-6 lg:grid-cols-[20rem_1fr]"><aside class="card p-5"><h2 class="font-black">Configurar reporte</h2><div class="mt-5 space-y-4"><label class="label">Establecimiento</label><select class="input"><option>Todos</option>@foreach($demo['establishments'] as $item)<option>{{ $item }}</option>@endforeach</select><label class="label">Desde</label><input type="date" class="input" value="2026-01-01"><label class="label">Hasta</label><input type="date" class="input" value="2026-10-03"><button class="btn-primary w-full" type="button" data-report-preview>Actualizar vista previa</button><button class="btn-secondary w-full" type="button" onclick="window.print()">Imprimir / guardar como PDF</button><button class="btn-secondary w-full" disabled title="Pendiente de integración real">Exportar Excel · Pendiente</button></div></aside><section class="card p-6 print-card" data-report-output><div class="border-b pb-5"><p class="eyebrow">Vista previa · Datos de demostración</p><h2 class="mt-2 text-2xl font-black" data-report-title>Resumen de casos</h2><p class="mt-1 text-sm text-slate-500">Período 01/01/2026 al 03/10/2026 · Todos los establecimientos</p></div><div class="mt-6 grid gap-4 sm:grid-cols-3"><div class="metric"><span>Total</span><strong>6</strong></div><div class="metric"><span>Activos</span><strong>5</strong></div><div class="metric"><span>Cerrados</span><strong>1</strong></div></div><table class="data-table mt-6"><thead><tr><th>Folio</th><th>Tipo</th><th>Establecimiento</th><th>Estado</th></tr></thead><tbody>@foreach($demo['cases']->take(4) as $case)<tr><td>{{ $case['id'] }}</td><td>{{ $case['type'] }}</td><td>{{ $case['establishment'] }}</td><td>{{ $case['status'] }}</td></tr>@endforeach</tbody></table></section></div>
    @elseif($module === 'profile')
        <div class="grid gap-6 lg:grid-cols-[1fr_22rem]"><section class="card p-6 sm:p-8"><h2 class="text-xl font-black">Datos personales</h2><dl class="mt-6 grid gap-6 sm:grid-cols-2"><div><dt>Nombre</dt><dd>{{ auth()->user()->name }}</dd></div><div><dt>RUT</dt><dd>{{ auth()->user()->rut }}</dd></div><div><dt>Correo</dt><dd>{{ auth()->user()->email }}</dd></div><div><dt>Cargo</dt><dd>{{ auth()->user()->job_title ?: 'Sin información' }}</dd></div><div><dt>Roles</dt><dd>{{ auth()->user()->roles->pluck('name')->join(' · ') }}</dd></div><div><dt>Establecimientos</dt><dd>{{ auth()->user()->establishments->pluck('name')->join(' · ') ?: 'Sin establecimiento asignado' }}</dd></div></dl><p class="mt-6 rounded-xl bg-sky-50 p-4 text-sm text-sky-900">Los datos de cuenta son solo de consulta en este prototipo.</p></section><aside class="card p-6"><h2 class="font-black">Preferencias visuales</h2><form class="mt-5 space-y-4" method="POST" action="{{ route('demo.action','profile') }}">@csrf<input type="hidden" name="action" value="Preferencias visuales guardadas"><label class="flex items-center justify-between gap-4">Vista compacta<input type="checkbox" class="h-5 w-5"></label><label class="flex items-center justify-between gap-4">Reducir animaciones<input type="checkbox" class="h-5 w-5"></label><label class="label">Densidad de tablas</label><select class="input"><option>Cómoda</option><option>Compacta</option></select><button class="btn-primary w-full">Guardar en demostración</button></form></aside></div>
    @elseif(in_array($module,['users','roles','establishments','settings']))
        @php
        $adminData = [
          'users'=>[['Carolina Medina','Prevencionista','CESFAM Los Aromos','Activo'],['Pedro Arancibia','Comité Paritario','SAR Central','Activo'],['Natalia Bustos','Jefatura Directa','CECOSF Norte','Suspendido']],
          'roles'=>[['Administrador','6 permisos','3 usuarios','Activo'],['Prevencionista','8 permisos','5 usuarios','Activo'],['Comité Paritario','6 permisos','12 usuarios','Activo']],
          'establishments'=>[['CESFAM Los Aromos','CESFAM','Av. Los Aromos 125','contacto@demo.test'],['SAR Central','SAR','Av. Central 980','sar@demo.test'],['CECOSF Norte','CECOSF','Pasaje Norte 44','norte@demo.test']],
          'settings'=>[['Tipos de caso','2 valores','Accidente · Enfermedad profesional','Activo'],['Categorías de control','5 valores','Eliminación · Sustitución · Ingeniería…','Activo'],['Estados de investigación','5 valores','Borrador · Revisión · Concluida…','Activo']],
        ][$module];
        @endphp
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Administración simulada:</strong> estas acciones no crean ni modifican usuarios, roles, establecimientos o parámetros reales.</div><div class="filter-bar"><input class="input" placeholder="Buscar" data-table-search><select class="input"><option>Todos los estados</option><option>Activo</option><option>Suspendido</option></select><button class="btn-primary" type="button" data-open-demo-modal>+ Nuevo registro</button></div><div class="card table-card"><table class="data-table"><thead><tr><th>Nombre</th><th>Tipo / rol</th><th>Alcance / detalle</th><th>Estado</th><th></th></tr></thead><tbody>@foreach($adminData as $row)<tr data-table-row><td class="font-bold">{{ $row[0] }}</td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td><span class="status {{ $row[3]==='Activo'?'status-approved':'status-pending' }}">{{ $row[3] }}</span></td><td><button class="text-link" type="button" data-open-demo-modal data-record="{{ $row[0] }}">Ver / editar</button></td></tr>@endforeach</tbody></table></div>
        @if($module==='roles')<div class="card p-6"><h2 class="font-black">Matriz visual de permisos</h2><div class="table-card mt-5"><table class="data-table"><thead><tr><th>Permiso</th><th>Administrador</th><th>Prevencionista</th><th>Comité Paritario</th></tr></thead><tbody>@foreach(['Ver casos','Investigar','Revisar expedientes','Gestionar medidas','Ver estadísticas','Administrar usuarios'] as $i=>$permission)<tr><td>{{ $permission }}</td><td><input type="checkbox" @checked($i===5)></td><td><input type="checkbox" @checked($i<5)></td><td><input type="checkbox" @checked(in_array($i,[0,1,3]))></td></tr>@endforeach</tbody></table></div></div>@endif
        <dialog class="demo-dialog" data-demo-modal><form method="POST" action="{{ route('demo.action',$module) }}" class="card p-6">@csrf<input type="hidden" name="action" value="Registro administrativo simulado guardado"><div class="flex items-start justify-between"><div><p class="eyebrow">Datos ficticios</p><h2 class="mt-1 text-xl font-black" data-modal-title>Nuevo registro</h2></div><button type="button" class="btn-secondary" data-close-demo-modal>×</button></div><div class="mt-6 grid gap-4"><label class="label">Nombre</label><input class="input" required><label class="label">Tipo o rol</label><select class="input"><option>Activo</option><option>En revisión</option></select><label class="label">Detalle</label><textarea class="input" rows="4"></textarea></div><button class="btn-primary mt-6 w-full">Guardar en demostración</button></form></dialog>
    @endif
</div>
</x-layouts.app>
