<section class='card hidden p-6 sm:p-8' data-step-panel='4'>
    <div class='flex items-start gap-4'><span class='flex size-11 shrink-0 items-center justify-center rounded-xl bg-blue-950 font-black text-white'>4</span><div><p class='eyebrow'>Confirmación</p><h2 class='mt-1 text-2xl font-black text-slate-950'>Recopilación del caso</h2><p class='mt-1 text-sm text-slate-600'>Revisa la información antes de continuar con el registro definitivo.</p></div></div>
    <div class='mt-7 grid gap-5 lg:grid-cols-2'>
        <article class='rounded-2xl border border-slate-200 p-5'><h3 class='font-black text-blue-950'>Empleador</h3><dl class='mt-4 grid gap-4 sm:grid-cols-2'><div><dt>Razón social</dt><dd data-review='employer_name'>Sin informar</dd></div><div><dt>RUT</dt><dd data-review='employer_rut'>Sin informar</dd></div><div><dt>Actividad económica</dt><dd data-review='economic_activity'>Sin informar</dd></div><div><dt>Administrador</dt><dd data-review='administrator'>Sin informar</dd></div><div><dt>Establecimiento</dt><dd data-review='establishment'>Sin informar</dd></div><div class='sm:col-span-2'><dt>Dirección</dt><dd data-review='employer_address'>Sin informar</dd></div></dl></article>
        <article class='rounded-2xl border border-slate-200 p-5'><h3 class='font-black text-blue-950'>Persona accidentada</h3><dl class='mt-4 grid gap-4 sm:grid-cols-2'><div><dt>Nombre</dt><dd data-review='worker_name'>Sin informar</dd></div><div><dt>RUT</dt><dd data-review='worker_rut'>Sin informar</dd></div><div><dt>Profesión u oficio</dt><dd data-review='job_title'>Sin informar</dd></div><div><dt>Centro</dt><dd data-review='workplace'>Sin informar</dd></div><div><dt>Fecha de nacimiento</dt><dd data-review='birth_date'>Sin informar</dd></div><div><dt>Tipo de contrato</dt><dd data-review='contract_type'>Sin informar</dd></div><div><dt>Categoría ocupacional</dt><dd data-review='occupational_category'>Sin informar</dd></div><div><dt>Fecha de ingreso</dt><dd data-review='hire_date'>Sin informar</dd></div></dl></article>
        <article class='rounded-2xl border border-slate-200 p-5 lg:col-span-2'><h3 class='font-black text-blue-950'>Circunstancias informadas</h3><dl class='mt-4 grid gap-4 md:grid-cols-3'><div><dt>Fecha</dt><dd data-review='event_date'>Sin informar</dd></div><div><dt>Lugar</dt><dd data-review='event_location'>Sin informar</dd></div><div class='md:col-span-3'><dt>Relato</dt><dd class='whitespace-pre-line' data-review='narrative'>Sin informar</dd></div></dl></article>
        <article class='rounded-2xl border border-sky-200 bg-sky-50 p-5 lg:col-span-2'><h3 class='font-black text-blue-950'>Evidencias adjuntas</h3><p class='mt-1 text-sm text-sky-900' data-review-evidence>Sin archivos adjuntos.</p></article>
    </div>
    <label class='mt-6 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950'><input type='checkbox' class='mt-1 accent-blue-800' data-confirm-review><span>Confirmo que revisé la información y entiendo que este caso ficticio quedará guardado solamente en este navegador.</span></label>
    <div class='mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between'><button type='button' class='btn-secondary' data-previous-step>← Volver y corregir</button><button type='submit' class='btn-primary inline-flex' data-finish disabled>Guardar caso ficticio</button></div>
    <div class='mt-4 hidden rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800' role='status' data-prototype-message>Caso ficticio guardado. Abriendo la lista…</div>
</section>
