<x-layouts.app title='Solicitudes de registro · GIATEP'>
<div class='flex flex-wrap items-end justify-between gap-4'><div><p class='eyebrow'>Administración</p><h1 class='mt-2 text-3xl font-bold'>Solicitudes de registro</h1><p class='mt-2 text-slate-600'>Revisa el acceso solicitado por Comité Paritario y Delegados de Seguridad.</p></div></div>
@if(session('status'))<div class='mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-800' role='status'>{{ session('status') }}</div>@endif
<div class='mt-6 grid gap-4 sm:grid-cols-3'><div class='stat-card'><span>Pendientes</span><strong>{{ $counts['pending'] ?? 0 }}</strong></div><div class='stat-card'><span>Aprobadas</span><strong>{{ $counts['approved'] ?? 0 }}</strong></div><div class='stat-card'><span>Rechazadas</span><strong>{{ $counts['rejected'] ?? 0 }}</strong></div></div>
<form method='GET' class='card mt-6 grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-5'>
<div class='xl:col-span-2'><label for='search' class='label'>Buscar por nombre o RUT</label><input id='search' name='search' value='{{ request('search') }}' class='input'></div>
<div><label for='status' class='label'>Estado</label><select id='status' name='status' class='input'><option value=''>Todos</option>@foreach(['pending' => 'Pendiente', 'approved' => 'Aprobada', 'rejected' => 'Rechazada'] as $value => $label)<option value='{{ $value }}' @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div>
<div><label for='establishment_id' class='label'>Establecimiento</label><select id='establishment_id' name='establishment_id' class='input'><option value=''>Todos</option>@foreach($establishments as $item)<option value='{{ $item->id }}' @selected((string) request('establishment_id') === (string) $item->id)>{{ $item->type }} · {{ $item->name }}</option>@endforeach</select></div>
<div><label for='requested_role' class='label'>Rol solicitado</label><select id='requested_role' name='requested_role' class='input'><option value=''>Todos</option><option value='delegado' @selected(request('requested_role') === 'delegado')>Delegado de Seguridad</option><option value='cphs' @selected(request('requested_role') === 'cphs')>Comité Paritario</option></select></div>
<div class='flex gap-2 xl:col-span-5'><button class='btn-primary' type='submit'>Aplicar filtros</button><a class='btn-secondary' href='{{ route('admin.registration-requests.index') }}'>Limpiar</a></div>
</form>
<div class='card mt-6 overflow-hidden'><div class='overflow-x-auto'><table class='w-full min-w-[900px] text-left text-sm'><thead class='bg-slate-100 text-xs uppercase tracking-wide text-slate-600'><tr><th>Nombre</th><th>RUT</th><th>Cargo</th><th>Establecimiento</th><th>Rol</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody class='divide-y divide-slate-200'>
@forelse($requests as $item)<tr><td class='font-bold'>{{ $item->name }}</td><td>{{ $item->rut }}</td><td>{{ $item->job_title }}</td><td>{{ $item->establishment->type }} · {{ $item->establishment->name }}</td><td>{{ $item->requested_role === 'delegado' ? 'Delegado de Seguridad' : 'Comité Paritario' }}</td><td>{{ $item->created_at->format('d/m/Y H:i') }}</td><td><span class='status status-{{ $item->status }}'>{{ ['pending' => 'Pendiente', 'approved' => 'Aprobada', 'rejected' => 'Rechazada'][$item->status] }}</span></td><td><a class='font-bold text-blue-800 hover:underline' href='{{ route('admin.registration-requests.index', array_merge(request()->query(), ['review' => $item->id])) }}'>Revisar</a></td></tr>
@empty<tr><td colspan='8' class='p-10 text-center text-slate-500'>No hay solicitudes que coincidan con los filtros.</td></tr>@endforelse
</tbody></table></div><div class='border-t border-slate-200 p-4'>{{ $requests->links() }}</div></div>
@if($selected)<div class='fixed inset-0 z-40 flex justify-end bg-slate-950/45' role='dialog' aria-modal='true' aria-labelledby='detail-title'><section class='h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl sm:p-8'><div class='flex items-start justify-between gap-4'><div><p class='eyebrow'>Detalle de solicitud</p><h2 id='detail-title' class='mt-2 text-2xl font-bold'>{{ $selected->name }}</h2></div><a href='{{ route('admin.registration-requests.index', request()->except('review')) }}' class='text-2xl' aria-label='Cerrar'>×</a></div>
<dl class='mt-7 grid gap-5 sm:grid-cols-2'><div><dt>RUT</dt><dd>{{ $selected->rut }}</dd></div><div><dt>Fecha</dt><dd>{{ $selected->created_at->format('d/m/Y H:i') }}</dd></div><div><dt>Cargo laboral</dt><dd>{{ $selected->job_title }}</dd></div><div><dt>Rol solicitado</dt><dd>{{ $selected->requested_role === 'delegado' ? 'Delegado de Seguridad' : 'Comité Paritario' }}</dd></div><div class='sm:col-span-2'><dt>Establecimiento</dt><dd>{{ $selected->establishment->type }} · {{ $selected->establishment->name }}</dd></div><div><dt>Correo</dt><dd>{{ $selected->email }}</dd></div><div><dt>Teléfono</dt><dd>{{ $selected->phone }}</dd></div></dl>
@if($selected->status === 'pending')
<div class='mt-8 border-t border-slate-200 pt-6'><form method='POST' action='{{ route('admin.registration-requests.update', $selected) }}' data-confirm='¿Confirmas la aprobación de {{ $selected->name }} como {{ $selected->requested_role === 'delegado' ? 'Delegado de Seguridad' : 'Comité Paritario' }} en {{ $selected->establishment->name }}?'>@csrf @method('PATCH')<input type='hidden' name='action' value='approve'><button class='btn-primary w-full'>Aprobar solicitud</button></form>
<form method='POST' action='{{ route('admin.registration-requests.update', $selected) }}' class='mt-5' data-confirm='¿Confirmas el rechazo de esta solicitud?'>@csrf @method('PATCH')<input type='hidden' name='action' value='reject'><label for='rejection_reason' class='label'>Motivo del rechazo</label><textarea id='rejection_reason' name='rejection_reason' rows='4' class='input' required>{{ old('rejection_reason') }}</textarea>@error('rejection_reason')<p class='error'>{{ $message }}</p>@enderror<button class='btn-danger mt-3 w-full'>Rechazar solicitud</button></form></div>
@else
<div class='mt-8 rounded-xl bg-slate-100 p-5'><p class='font-bold'>Solicitud {{ $selected->status === 'approved' ? 'aprobada' : 'rechazada' }}</p><p class='mt-1 text-sm text-slate-600'>Resuelta por {{ $selected->resolver?->name ?? 'Administrador no disponible' }} el {{ $selected->resolved_at?->format('d/m/Y H:i') }}.</p>@if($selected->rejection_reason)<p class='mt-3 text-sm'><strong>Motivo:</strong> {{ $selected->rejection_reason }}</p>@endif</div>
@endif
</section></div>@endif
</x-layouts.app>
