<x-layouts.app title="Inicio · GIATEP">
<div class="mx-auto max-w-[1500px] space-y-6">
    <section class="brand-panel rounded-3xl p-6 text-white shadow-lg sm:p-10"><div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-sm font-bold uppercase tracking-widest text-sky-200">{{ $dashboardProfile['label'] }} · Prototipo visual</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Hola, {{ $user->name }}</h1><p class="mt-3 max-w-2xl text-sky-100">{{ $dashboardProfile['message'] }}</p></div><div class="rounded-2xl bg-white/10 px-5 py-4 backdrop-blur"><p class="text-xs font-bold uppercase tracking-wider text-sky-200">Alcance actual</p><p class="mt-1 font-bold">{{ $user->establishments->pluck('name')->join(' · ') ?: 'Sin establecimiento asignado' }}</p></div></div></section>
    @if($user->hasPermission('cases.read') || $user->hasPermission('investigations.read'))<section><div class="mb-4 flex items-end justify-between"><div><p class="eyebrow">Datos de demostración</p><h2 class="mt-1 text-2xl font-black">Resumen operativo</h2></div><span class="text-xs text-slate-500">Actualizado hoy</span></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        @if($user->hasPermission('cases.read'))<a class="metric metric-link" href="{{ route('modules.cases.index') }}"><span>Casos registrados</span><strong>{{ $metrics['cases'] }}</strong><small>Ver listado →</small></a>@endif
        @if($user->hasPermission('investigations.read'))<a class="metric metric-link" href="{{ route('modules.investigations.index') }}"><span>Investigaciones pendientes</span><strong>{{ $metrics['investigations_pending'] }}</strong><small>Revisar expedientes →</small></a>@endif
        @if($user->hasPermission('observations.read'))<a class="metric metric-link" href="{{ route('modules.observations.index') }}"><span>Con observaciones</span><strong>{{ $metrics['with_observations'] }}</strong><small>Ver correcciones →</small></a>@endif
        @if($user->hasPermission('measures.read'))<a class="metric metric-link" href="{{ route('modules.measures.index') }}"><span>Medidas próximas</span><strong>{{ $metrics['measures_due_soon'] }}</strong><small>Plan de acción →</small></a><a class="metric metric-danger metric-link" href="{{ route('modules.measures.index') }}"><span>Medidas vencidas</span><strong>{{ $metrics['measures_overdue'] }}</strong><small>Requieren atención →</small></a>@endif
    </div></section>@endif
    @if($user->hasPermission('cases.read') || $user->hasPermission('investigations.read'))<section class="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div class="card p-6"><div class="flex items-center justify-between"><div><p class="eyebrow">Tendencia de ejemplo</p><h2 class="mt-1 text-xl font-black">Registros por mes</h2></div><span class="status status-pending">Últimos 6 meses</span></div><div class="mini-columns mt-8">@foreach(['May'=>2,'Jun'=>1,'Jul'=>3,'Ago'=>4,'Sep'=>6,'Oct'=>2] as $month=>$value)<div><span style="height:{{ 20+$value*12 }}px"></span><strong>{{ $value }}</strong><small>{{ $month }}</small></div>@endforeach</div></div><div class="card p-6"><p class="eyebrow">Trazabilidad</p><h2 class="mt-1 text-xl font-black">Actividad reciente</h2><ul class="timeline mt-6">@foreach($demo['activity'] as $item)<li><strong>{{ $item['text'] }}</strong><span>{{ $item['time'] }}</span></li>@endforeach</ul></div></section>@else<section class="grid gap-4 md:grid-cols-3"><a href="{{ route('admin.registration-requests.index') }}" class="metric metric-link"><span>Solicitudes de acceso</span><strong>3</strong><small>Revisar pendientes →</small></a><a href="{{ route('admin.users.index') }}" class="metric metric-link"><span>Usuarios ficticios</span><strong>3</strong><small>Abrir boceto →</small></a><a href="{{ route('admin.establishments.index') }}" class="metric metric-link"><span>Establecimientos ficticios</span><strong>4</strong><small>Ver catálogo →</small></a></section>@endif
    <section><p class="eyebrow">Accesos rápidos</p><h2 class="mt-1 text-2xl font-black">Actividad autorizada</h2>@if($availableActions->isEmpty())<div class="empty-state mt-5">No tienes módulos operativos asignados. Usa el menú para acceder a las funciones administrativas o a tu perfil.</div>@else<div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($availableActions as $action)<a href="{{ route($action['route']) }}" class="card group p-6 transition hover:-translate-y-0.5 hover:border-sky-300 hover:shadow-md"><span class="module-icon">{{ mb_substr($action['title'],0,1) }}</span><h3 class="mt-4 text-lg font-black group-hover:text-blue-800">{{ $action['title'] }}</h3><p class="mt-2 text-sm leading-6 text-slate-600">{{ $action['description'] }}</p><span class="mt-4 inline-block font-bold text-sky-700">Abrir módulo →</span></a>@endforeach</div>@endif</section>
    <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Regla pendiente de definición:</strong> las estadísticas globales y exportaciones se muestran solo a Prevencionistas y Alta Dirección en esta demostración.</div>
</div>
</x-layouts.app>
