@php
    $yesNoNa = ['yes' => 'Sí', 'no' => 'No', 'na' => 'No aplica'];
    $facilityConditions = ['Protección frente a contactos eléctricos directos defectuosa o inexistente', 'Protección frente a contactos eléctricos indirectos defectuosa o inexistente', 'Focos de ignición no controlados', 'Inexistencia o insuficiencia de compartimentación de áreas de riesgo', 'Sistemas de detección de incendios o alarmas incorrectos', 'Instalaciones de extinción de incendios incorrectas'];
    $equipmentConditions = ['Órganos móviles alejados del punto de operación accesible', 'Zona de operación desprotegida o parcialmente protegida', 'Arranque intempestivo', 'Anulación de protectores', 'Inexistencia de elementos o dispositivos de control', 'Ausencia de alarmas', 'Paro de emergencia inexistente o no accesible', 'Ausencia de medios para la consignación de la máquina', 'Ausencia o deficiencia de protecciones antivuelco', 'Deficiencia de protecciones contra caída de materiales'];
    $materialConditions = ['Materiales muy pesados en relación con los medios de protección utilizados', 'Materiales con aristas o perfiles cortantes', 'Inestabilidad en almacenamiento por apilado', 'Manipulación manual de cargas'];
    $environmentFactors = ['Agresión térmica por frío o calor', 'Nivel de ruido elevado', 'Iluminación incorrecta', 'Nivel de vibración que provoca pérdida de tacto o fatiga', 'Exposición ambiental a sustancias o productos tóxicos', 'Exposición a contaminantes biológicos', 'Agresiones por seres vivos'];
    $musculoskeletalFactors = ['Exceso de esfuerzo físico', 'Manipulación de cargas', 'Posturas forzadas', 'Movimientos repetitivos'];
    $organizationFactors = ['Simultaneidad de tareas por el mismo operario', 'Trabajo a velocidad o ritmo elevado', 'Primas por productividad', 'Trabajo monótono', 'Trabajo aislado o solitario', 'Falta de supervisión', 'Trabajo a turnos', 'Trabajo nocturno', 'Trabajo temporal', 'Exceso de horas de trabajo', 'Exceso de esfuerzo mental'];
@endphp

<div class="mt-7 space-y-6" data-adapted-questionnaire>
    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Tarea</legend><div class="space-y-5">
        <div data-branch-question data-branch-value="yes"><p class="label">1. ¿La tarea que desarrollaba era propia de su puesto de trabajo?</p><div class="flex flex-wrap gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="task_own_job" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div>
        <div data-branch-question data-branch-value="yes"><p class="label">2. ¿La tarea desarrollada era habitual?</p><div class="flex flex-wrap gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="task_habitual" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-4 hidden grid gap-5 md:grid-cols-2" data-branch-panel><div data-branch-question data-branch-value="no"><p class="label">2.1 ¿Se realizaba de la misma manera que normalmente?</p><div class="flex gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="task_same_way" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-3 hidden" data-branch-panel><p class="label">2.3 Motivo de realizarla de diferente manera</p>@foreach(['No era posible realizarla de la forma habitual', 'Desconocía la forma habitual de realizarla', 'Había recibido instrucciones de realizarla de esta manera'] as $reason)<label class="mb-2 flex gap-2 text-sm"><input type="checkbox" name="task_change_reasons[]" value="{{ $reason }}">{{ $reason }}</label>@endforeach<label class="block"><span class="label">Otro</span><input class="input" name="task_change_other"></label></div></div><div><p class="label">2.2 ¿Era posible que ocurriera el accidente realizando la tarea de forma habitual?</p><div class="flex gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="task_usual_accident_possible" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div></div></div>
        <div><p class="label">3. ¿Con qué frecuencia había desarrollado esta misma tarea?</p><div class="grid gap-2 sm:grid-cols-3">@foreach(['Era la primera vez', 'De manera esporádica', 'Frecuentemente', 'No aplica'] as $frequency)<label class="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><input type="radio" name="task_frequency" value="{{ $frequency }}">{{ $frequency }}</label>@endforeach</div></div>
        <div data-branch-question data-branch-value="yes"><p class="label">4. ¿Había recibido instrucciones sobre cómo realizar la tarea?</p><div class="flex flex-wrap gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="instructions_received" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-4 hidden grid gap-5 md:grid-cols-3" data-branch-panel><div><p class="label">Tipo de instrucciones</p>@foreach(['Escritas','Verbales','Ambas'] as $option)<label class="mb-2 flex gap-2 text-sm"><input type="checkbox" name="instruction_type[]" value="{{ $option }}">{{ $option }}</label>@endforeach</div><div><p class="label">¿De quién las recibió?</p>@foreach(['Empleador','Jefe','Encargado','Compañeros'] as $option)<label class="mb-2 flex gap-2 text-sm"><input type="checkbox" name="instruction_source[]" value="{{ $option }}">{{ $option }}</label>@endforeach</div><div><p class="label">¿Realizaba la tarea de acuerdo con esas instrucciones?</p><div class="flex gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="followed_instructions" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div></div></div>
        <div data-branch-question data-branch-value="yes"><p class="label">5. ¿La tarea se realizaba habitualmente con equipo de protección personal?</p><div class="flex flex-wrap gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="ppe_habitual" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-4 hidden grid gap-5 md:grid-cols-3" data-branch-panel><label><span class="label">Indique cuáles</span><textarea class="input" name="ppe_description" rows="3"></textarea></label>@foreach(['¿El EPP era adecuado al riesgo?', '¿Utilizaba el EPP al momento del accidente?', '¿Otro EPP habría evitado el accidente?'] as $index => $question)<div><p class="label">5.{{ $index + 1 }} {{ $question }}</p><div class="flex gap-2">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="ppe_followup_{{ $index }}" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div>@endforeach</div></div>
    </div></fieldset>

    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Lugar</legend><div class="space-y-5"><div data-branch-question data-branch-value="yes"><p class="label">6. ¿La tarea se realizaba en el lugar habitual de trabajo?</p><div class="flex gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="usual_place" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-4 hidden grid gap-5 md:grid-cols-2" data-branch-panel><div><p class="label">6.1 ¿Era posible que ocurriera el accidente en el lugar habitual?</p><div class="flex gap-2">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="usual_place_possible" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div><label><span class="label">6.2 Motivo de realizar la tarea en otro lugar</span><textarea class="input" name="different_place_reason" rows="3"></textarea></label></div></div><div><p class="label">7. Circunstancias asociadas a las instalaciones</p><div class="grid gap-2 md:grid-cols-2">@foreach($facilityConditions as $condition)<label class="flex gap-2 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" name="facility_conditions[]" value="{{ $condition }}">{{ $condition }}</label>@endforeach</div><label class="mt-3 block"><span class="label">Otros</span><textarea class="input" name="facility_other" rows="2"></textarea></label></div></div></fieldset>

    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Tiempo</legend><div class="space-y-5"><div data-branch-question data-branch-value="yes"><p class="label">8. ¿La tarea se realizaba en el momento habitual?</p><div class="flex gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="usual_time" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-4 hidden grid gap-5 md:grid-cols-2" data-branch-panel><div><p class="label">8.1 ¿Era posible que ocurriera el accidente en el momento habitual?</p><div class="flex gap-2">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="usual_time_possible" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div><label><span class="label">8.2 Motivo de realizar la tarea en otro momento</span><textarea class="input" name="different_time_reason" rows="3"></textarea></label></div></div><div><p class="label">9. Circunstancias de tiempo asociadas</p><div class="grid gap-2 sm:grid-cols-2">@foreach(['Realizando horas extra','Doblando un turno','Jornada superior a la ordinaria','Después de una pausa','Otro'] as $condition)<label class="flex gap-2 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" name="time_conditions[]" value="{{ $condition }}">{{ $condition }}</label>@endforeach</div></div></div></fieldset>

    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Equipo de trabajo</legend><div class="space-y-5"><div data-branch-question data-branch-value="yes"><p class="label">10. ¿Se utilizaban equipos de trabajo durante la tarea?</p><div class="flex gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="equipment_used" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-4 hidden space-y-4" data-branch-panel><label><span class="label">Indique cuáles</span><textarea class="input" name="equipment_description" rows="2"></textarea></label><div class="grid gap-5 md:grid-cols-2">@foreach(['¿Era el equipo habitual para la tarea?', '¿Era posible que ocurriera el accidente utilizando el equipo habitual?'] as $index => $question)<div><p class="label">10.{{ $index + 1 }} {{ $question }}</p><div class="flex gap-2">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="equipment_followup_{{ $index }}" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div>@endforeach</div><label><span class="label">10.3 Motivo de no utilizar el equipo habitual</span><textarea class="input" name="equipment_reason" rows="3"></textarea></label></div></div><div><p class="label">11. Circunstancias asociadas a equipos de trabajo</p><div class="grid gap-2 md:grid-cols-2">@foreach($equipmentConditions as $condition)<label class="flex gap-2 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" name="equipment_conditions[]" value="{{ $condition }}">{{ $condition }}</label>@endforeach</div><label class="mt-3 block"><span class="label">Otros</span><textarea class="input" name="equipment_other" rows="2"></textarea></label></div></div></fieldset>

    <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">Materiales, sustancias y productos</legend><div class="space-y-5"><div data-branch-question data-branch-value="yes"><p class="label">12. ¿Estaba involucrada alguna sustancia o producto?</p><div class="flex gap-3">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="substance_involved" value="{{ $value }}">{{ $label }}</label>@endforeach</div><div class="mt-4 hidden grid gap-5 md:grid-cols-3" data-branch-panel><div><p class="label">12.1 Tipo de sustancia o producto</p>@foreach(['Explosivo','Inflamable','Tóxico','Corrosivo','Irritante','Sensibilizante','Reacciona peligrosamente con agua','Otro'] as $type)<label class="mb-2 flex gap-2 text-sm"><input type="checkbox" name="substance_types[]" value="{{ $type }}">{{ $type }}</label>@endforeach</div><div><p class="label">12.2 ¿Era de uso habitual?</p><div class="flex gap-2">@foreach($yesNoNa as $value => $label)<label class="btn-secondary gap-2"><input type="radio" name="substance_habitual" value="{{ $value }}">{{ $label }}</label>@endforeach</div></div><label><span class="label">12.3 Motivo de utilizar una sustancia no habitual</span><textarea class="input" name="substance_reason" rows="4"></textarea></label></div></div><div><p class="label">13. Circunstancias asociadas a materiales</p><div class="grid gap-2 md:grid-cols-2">@foreach($materialConditions as $condition)<label class="flex gap-2 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" name="material_conditions[]" value="{{ $condition }}">{{ $condition }}</label>@endforeach</div></div></div></fieldset>

    @foreach([['14. Ambiente de trabajo', 'environment_factor', $environmentFactors], ['15. Factores musculoesqueléticos', 'musculoskeletal_factor', $musculoskeletalFactors], ['16. Organización del trabajo', 'organization_factor', $organizationFactors]] as [$title, $name, $factors])
        <fieldset class="rounded-xl border border-slate-200 p-5"><legend class="px-2 font-black text-blue-950">{{ $title }}</legend><div class="mt-3 overflow-x-auto"><table class="data-table min-w-[680px]"><thead><tr><th>Factor o condición</th><th>Presente durante el accidente</th><th>Presencia habitual</th></tr></thead><tbody>@foreach($factors as $index => $factor)<tr><td>{{ $factor }}</td><td><div class="flex gap-4"><label class="flex gap-2"><input type="radio" name="{{ $name }}_event_{{ $index }}" value="yes">Sí</label><label class="flex gap-2"><input type="radio" name="{{ $name }}_event_{{ $index }}" value="no">No</label><label class="flex gap-2"><input type="radio" name="{{ $name }}_event_{{ $index }}" value="na">N/A</label></div></td><td><div class="flex gap-4"><label class="flex gap-2"><input type="radio" name="{{ $name }}_usual_{{ $index }}" value="yes">Sí</label><label class="flex gap-2"><input type="radio" name="{{ $name }}_usual_{{ $index }}" value="no">No</label><label class="flex gap-2"><input type="radio" name="{{ $name }}_usual_{{ $index }}" value="na">N/A</label></div></td></tr>@endforeach</tbody></table></div><label class="mt-4 block"><span class="label">Otros antecedentes</span><textarea class="input" name="{{ $name }}_other" rows="2"></textarea></label></fieldset>
    @endforeach

    <label class="block"><span class="label">Observaciones generales de la entrevista</span><textarea class="input" name="interview_observations" rows="5"></textarea></label>
</div>
